// backend/scripts/generateFontBase64.js
// Run: node backend/scripts/generateFontBase64.js

const fs = require("fs");
const path = require("path");

// Font files - place these in backend/fonts/
const FONT_FILES = {
  notoSansEthiopic: "./fonts/NotoSansEthiopic-Regular.ttf",
  notoSansEthiopicBold: "./fonts/NotoSansEthiopic-Bold.ttf",
  roboto: "./fonts/Roboto-Regular.ttf",
  robotoBold: "./fonts/Roboto-Bold.ttf",
};

function convertFontToBase64(filePath) {
  try {
    if (!fs.existsSync(filePath)) {
      console.warn(`⚠️ Font file not found: ${filePath}`);
      return null;
    }
    const fontBuffer = fs.readFileSync(filePath);
    return fontBuffer.toString("base64");
  } catch (error) {
    console.error(`Error converting ${filePath}:`, error.message);
    return null;
  }
}

function generateFontBase64File() {
  console.log("🔄 Generating font base64 data...");

  const base64Data = {};

  for (const [name, filePath] of Object.entries(FONT_FILES)) {
    console.log(`📥 Converting ${name}...`);
    const base64 = convertFontToBase64(filePath);
    if (base64) {
      base64Data[name] = base64;
      console.log(
        `✅ ${name} converted (${Math.round(base64.length / 1024)}KB)`,
      );
    } else {
      console.warn(`⚠️ ${name} skipped`);
    }
  }

  // Generate the output file for frontend
  const output = `// Auto-generated font base64 data
// Generated on: ${new Date().toISOString()}
// Do not edit this file directly

export const FONT_BASE64 = ${JSON.stringify(base64Data, null, 2)};
`;

  const outputPath = path.join(
    __dirname,
    "../../../frontend/src/utils/pdf/fonts/fontBase64.js",
  );

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, output);
  console.log(`✅ Font base64 file generated at: ${outputPath}`);

  // Also generate a smaller version for the backend (if needed for server-side PDF)
  const backendOutputPath = path.join(__dirname, "../utils/fontBase64.js");
  fs.writeFileSync(backendOutputPath, output);
  console.log(`✅ Backend font file generated at: ${backendOutputPath}`);
}

// Create fonts directory if it doesn't exist
const fontsDir = path.join(__dirname, "../fonts");
if (!fs.existsSync(fontsDir)) {
  fs.mkdirSync(fontsDir, { recursive: true });
  console.log(`📁 Created fonts directory: ${fontsDir}`);
}

// Run the conversion
generateFontBase64File();
