// frontend/src/utils/pdf/reports/dailyReport.js
import { createPDF } from "../pdfEngine";
import { encodeText, isAmharic, detectLanguage } from "../language";
import { loadFonts, FONT_NAMES } from "../fontLoader";

// ─────────────────────────────────────────────────────────────────────────────
// ✅ Ethiopian calendar conversion (Gregorian → Ethiopian)
// ─────────────────────────────────────────────────────────────────────────────
const ETHIOPIAN_MONTHS_AM = [
  "መስከረም",
  "ጥቅምት",
  "ህዳር",
  "ታህሳስ",
  "ጥር",
  "የካቲት",
  "መጋቢት",
  "ሚያዝያ",
  "ግንቦት",
  "ሰኔ",
  "ሐምሌ",
  "ነሐሴ",
  "ጳጉሜ",
];

const JDN_EPOCH_OFFSET_AMETE_MIHRET = 1723856;

function gregorianToJDN(year, month, day) {
  const a = Math.floor((14 - month) / 12);
  const y = year + 4800 - a;
  const m = month + 12 * a - 3;
  return (
    day +
    Math.floor((153 * m + 2) / 5) +
    365 * y +
    Math.floor(y / 4) -
    Math.floor(y / 100) +
    Math.floor(y / 400) -
    32045
  );
}

function toEthiopianDate(date = new Date()) {
  const jdn = gregorianToJDN(
    date.getFullYear(),
    date.getMonth() + 1,
    date.getDate(),
  );
  const offsetDays = jdn - JDN_EPOCH_OFFSET_AMETE_MIHRET;
  const r = offsetDays % 1461;
  const n = (r % 365) + 365 * Math.floor(r / 1460);
  const year =
    4 * Math.floor(offsetDays / 1461) +
    Math.floor(r / 365) -
    Math.floor(r / 1460);
  const month = Math.floor(n / 30) + 1;
  const day = (n % 30) + 1;
  return { year, month, day, monthName: ETHIOPIAN_MONTHS_AM[month - 1] };
}

function formatEthiopianDate(date = new Date()) {
  const { year, day, monthName } = toEthiopianDate(date);
  return `${monthName} ${day} ቀን ${year} ዓ.ም`;
}
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate Daily Report PDF with full Amharic support
 * @param {Array} rows - Array of report rows with dept, service, male, female, total
 * @param {string} date - Report date string
 * @param {Object} t - Translation function object
 * @param {Object} options - Additional options for PDF generation
 * @param {string} options.filename - Custom filename (optional)
 * @param {string} options.footerText - Custom footer text (optional)
 * @param {boolean} options.showWatermark - Show watermark (optional)
 * @param {string} options.language - Output language: 'am', 'en', 'om'
 */
export const generateDailyReportPDF = async (rows, date, t, options = {}) => {
  try {
    console.log("📄 Generating Daily Report PDF...");

    if (!rows || rows.length === 0) {
      throw new Error("No data to export");
    }

    // Filter valid rows
    const validRows = rows.filter((r) => r.dept || r.service);

    if (validRows.length === 0) {
      throw new Error("No valid data to export");
    }

    // ─── 🔍 AUTO-DETECT LANGUAGE USING detectLanguage ───
    const sampleText = validRows
      .slice(0, 5)
      .map((r) => (r.dept || "") + " " + (r.service || ""))
      .join(" ");

    const detected = detectLanguage(sampleText);
    console.log(`🔍 Detected language from content: ${detected}`);

    let lang = options?.language || "am";

    if (!options?.language) {
      if (detected === "amharic") {
        lang = "am";
        console.log(`🔍 Auto-detected Amharic content, using Amharic font`);
      } else if (detected === "english") {
        lang = "en";
        console.log(`🔍 Auto-detected English content, using English font`);
      } else if (detected === "mixed") {
        lang = "am";
        console.log(`🔍 Mixed content detected, defaulting to Amharic font`);
      } else {
        lang = "am";
        console.log(`🔍 Language not detected, defaulting to Amharic`);
      }
    } else {
      console.log(`📄 Using user-specified language: ${lang.toUpperCase()}`);
    }
    // ─── END OF AUTO-DETECTION ───

    // Language-specific labels
    const LABELS = {
      am: {
        title: "ዕለታዊ ሪፖርት",
        subtitle: "የአዲስ መሶብ የአንድ ማዕከል አገልግሎት",
        reportDate: "የሪፖርቱ ቀን",
        generatedOn: "የተዘጋጀበት ቀን",
        colNo: "ተ/ቁ",
        colDept: "ዘርፍ",
        colService: "አገልግሎት",
        colMale: "ወንድ",
        colFemale: "ሴት",
        colTotal: "ድምር",
        grandTotal: "ጠቅላላ ድምር",
        footer: "በአዲስ መሶብ የአንድ ማዕከል አገልግሎት ማእከል የተዘጋጀ",
        generatedBy: "ገጽ",
        of: "ከ",
        page: "ገጽ",
      },
      en: {
        title: "Daily Report",
        subtitle: "A-MESOB One-Stop Service Center",
        reportDate: "Report Date",
        generatedOn: "Generated On",
        colNo: "#",
        colDept: "Department",
        colService: "Service",
        colMale: "Male",
        colFemale: "Female",
        colTotal: "Total",
        grandTotal: "Grand Total",
        footer: "Generated by A-MESOB One-Stop Service Center",
        generatedBy: "Page",
        of: "of",
        page: "Page",
      },
      om: {
        title: "Guyyaa Guyyaa Oduu",
        subtitle: "A-MESOB One-Stop Tajaajila",
        reportDate: "Guyyaa Oduu",
        generatedOn: "Guyyaa Qophaa'ame",
        colNo: "#",
        colDept: "Kutaa",
        colService: "Tajaajila",
        colMale: "Dhiira",
        colFemale: "Dubartii",
        colTotal: "Waliigala",
        grandTotal: "Waliigala Guutuu",
        footer: "A-MESOB One-Stop Tajaajila Keessatti Qophaa'e",
        generatedBy: "Fuula",
        of: "keessaa",
        page: "Fuula",
      },
    };

    const labels = LABELS[lang] || LABELS.am;

    // Create PDF engine with daily theme
    const engine = createPDF({
      orientation: "landscape",
      theme: "daily",
    });

    const doc = engine.getDoc();

    loadFonts(doc, { silent: false });

    const setSmartFont = (text, bold = false) => {
      try {
        const hasAmharic = isAmharic(text);
        const style = bold ? "bold" : "normal";

        if (hasAmharic) {
          if (doc.__hasEthiopicFont) {
            doc.setFont(FONT_NAMES.ethiopic, style);
          } else {
            doc.setFont("helvetica", style);
          }
        } else {
          if (doc.__hasLatinFont) {
            doc.setFont(FONT_NAMES.latin, style);
          } else {
            doc.setFont("helvetica", style);
          }
        }
      } catch (error) {
        console.warn("Font fallback:", error.message);
        doc.setFont("helvetica", bold ? "bold" : "normal");
      }
    };

    // ─── Set document metadata ────────────────────────────────────────────────
    try {
      doc.setProperties({
        title: `${labels.title} - ${date}`,
        author: options?.author || "A-MESOB One-Stop Service Center",
        subject:
          options?.subject || `${labels.title} (${labels.reportDate}: ${date})`,
        keywords: options?.keywords || "daily, report, service, Amharic",
        creator: "A-MESOB PDF Generator",
      });
    } catch (metadataError) {
      console.debug("Could not set document metadata:", metadataError.message);
    }

    // ─── Title ────────────────────────────────────────────────────────────────
    setSmartFont(labels.title, true);
    doc.setFontSize(20);
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;
    doc.text(encodeText(labels.title), pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 12;

    // ─── Subtitle ──────────────────────────────────────────────────────────────
    setSmartFont(labels.subtitle, false);
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(encodeText(labels.subtitle), pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 10;
    doc.setTextColor(0, 0, 0);

    // ─── Report Date ──────────────────────────────────────────────────────────
    const reportDate = date || new Date().toISOString().split("T")[0];
    const displayDate = reportDate.split("-").reverse().join("/");

    // ✅ FIX: Encode the full string properly
    const reportDateText = `${labels.reportDate}: ${displayDate}`;
    setSmartFont(reportDateText, false);
    doc.setFontSize(11);
    doc.text(encodeText(reportDateText), pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 8;

    // ─── ✅ Generated On (Ethiopian calendar) ────────────────────────────────
    const ethiopianDate = formatEthiopianDate(new Date());
    const generatedOnText = `${labels.generatedOn}: ${ethiopianDate}`;

    // ✅ FIX: Encode the full string properly and ensure font is set
    setSmartFont(generatedOnText, false);
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(encodeText(generatedOnText), pageWidth / 2, yPos, {
      align: "center",
    });
    doc.setTextColor(0, 0, 0);
    yPos += 10;

    // ─── Draw separator line ──────────────────────────────────────────────────
    doc.setDrawColor(26, 107, 74);
    doc.setLineWidth(0.5);
    doc.line(15, yPos, pageWidth - 15, yPos);
    yPos += 10;

    // ─── Calculate Totals ─────────────────────────────────────────────────────
    const grandTotal = validRows.reduce(
      (sum, row) => sum + (row.total || 0),
      0,
    );
    const grandMale = validRows.reduce((sum, row) => sum + (row.male || 0), 0);
    const grandFemale = validRows.reduce(
      (sum, row) => sum + (row.female || 0),
      0,
    );

    // ─── Table ─────────────────────────────────────────────────────────────────
    const head = [
      [
        labels.colNo,
        labels.colDept,
        labels.colService,
        labels.colMale,
        labels.colFemale,
        labels.colTotal,
      ],
    ];

    const body = validRows.map((row, idx) => [
      `${idx + 1}`,
      encodeText(row.dept || "—"),
      encodeText(row.service || "—"),
      row.male || 0,
      row.female || 0,
      row.total || 0,
    ]);

    const foot = [
      ["", "", labels.grandTotal, grandMale, grandFemale, grandTotal],
    ];

    const autoTable = (await import("jspdf-autotable")).default;

    autoTable(doc, {
      startY: yPos,
      head: head,
      body: body,
      foot: foot,
      margin: { left: 15, right: 15 },
      theme: options?.tableTheme || "striped",
      headStyles: {
        fillColor: [26, 107, 74],
        textColor: [255, 255, 255],
        fontSize: options?.headerFontSize || 10,
        fontStyle: "bold",
        halign: "center",
        valign: "middle",
        cellPadding: 5,
      },
      bodyStyles: {
        fontSize: options?.bodyFontSize || 9,
        cellPadding: 4,
        halign: "center",
        valign: "middle",
      },
      footStyles: {
        fillColor: [240, 247, 244],
        textColor: [26, 107, 74],
        fontStyle: "bold",
        fontSize: options?.footerFontSize || 10,
        halign: "center",
        valign: "middle",
      },
      columnStyles: {
        0: { cellWidth: 18, halign: "center" },
        1: { cellWidth: "auto" },
        2: { cellWidth: "auto" },
        3: { cellWidth: 25, halign: "center" },
        4: { cellWidth: 25, halign: "center" },
        5: { cellWidth: 30, halign: "center" },
      },
      didParseCell: (data) => {
        const cellText = String(data.cell.raw || "");
        const hasAmharic = /[\u1200-\u137F]/.test(cellText);

        if (hasAmharic) {
          data.cell.styles.font = doc.__hasEthiopicFont
            ? FONT_NAMES.ethiopic
            : "helvetica";
        } else {
          data.cell.styles.font = doc.__hasLatinFont
            ? FONT_NAMES.latin
            : "helvetica";
        }

        data.cell.raw = encodeText(cellText);
      },
      styles: {
        font: doc.__hasLatinFont ? FONT_NAMES.latin : "helvetica",
      },
      pageBreak: "auto",
      tableWidth: "auto",
    });

    yPos = doc.lastAutoTable?.finalY + 10 || yPos + 50;

    // ─── Add Watermark if requested ──────────────────────────────────────────
    if (options?.showWatermark) {
      try {
        const watermarkText = options?.watermarkText || labels.title;
        const pageCount = doc.internal.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
          doc.setPage(i);

          let gStateApplied = false;
          try {
            doc.saveGraphicsState();
            doc.setGState(new doc.GState({ opacity: 0.06 }));
            gStateApplied = true;
          } catch (gStateError) {
            console.debug(
              "GState opacity unsupported, falling back to light color:",
              gStateError.message,
            );
          }

          setSmartFont(watermarkText, false);
          doc.setFontSize(options?.watermarkSize || 50);
          doc.setTextColor(
            gStateApplied ? 150 : 225,
            gStateApplied ? 150 : 225,
            gStateApplied ? 150 : 225,
          );
          doc.text(
            encodeText(watermarkText),
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() / 2,
            {
              align: "center",
              angle: options?.watermarkAngle || -45,
            },
          );

          if (gStateApplied) {
            try {
              doc.restoreGraphicsState();
            } catch (restoreError) {
              console.debug(
                "restoreGraphicsState failed:",
                restoreError.message,
              );
            }
          }
        }
        doc.setTextColor(0, 0, 0);
      } catch (watermarkError) {
        console.warn("Watermark addition failed:", watermarkError.message);
      }
    }

    // ─── Footer ────────────────────────────────────────────────────────────────
    const footerText = options?.footerText || labels.footer;
    const pageCount = doc.internal.getNumberOfPages();
    const footerY = doc.internal.pageSize.getHeight() - 12;

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(15, footerY - 4, pageWidth - 15, footerY - 4);

      setSmartFont(footerText, false);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(encodeText(footerText), pageWidth / 2, footerY, {
        align: "center",
      });

      doc.text(
        `${labels.page} ${i} ${labels.of} ${pageCount}`,
        pageWidth - 15,
        footerY,
        { align: "right" },
      );
    }

    // ─── Save ──────────────────────────────────────────────────────────────────
    const safeDate = reportDate.replace(/\//g, "-");
    const langSuffix = lang === "am" ? "_am" : lang === "om" ? "_om" : "_en";
    const filename =
      options?.filename || `AMESOB_DailyReport${langSuffix}_${safeDate}.pdf`;
    engine.save(filename);

    console.log(
      `✅ Daily Report PDF generated successfully in ${lang.toUpperCase()}!`,
    );
    console.log(`📄 Saved as: ${filename}`);
    console.log(
      `📊 Total rows: ${validRows.length}, Grand total: ${grandTotal}`,
    );

    return true;
  } catch (error) {
    console.error("❌ Daily Report PDF Error:", error.message);
    console.error("Stack trace:", error.stack);
    throw error;
  }
};

export default generateDailyReportPDF;
