// frontend/src/utils/pdf/reports/dailyReport.js
import { createPDF } from "../pdfEngine";
import { encodeText, isAmharic, detectLanguage } from "../language";
import { loadFonts, FONT_NAMES } from "../fontLoader";

/**
 * Generate Daily Report PDF with full Amharic support
 * @param {Array} rows - Array of report rows with dept, service, male, female, total
 * @param {string} date - Report date string
 * @param {Object} t - Translation function object
 * @param {Object} options - Additional options for PDF generation
 * @param {string} options.filename - Custom filename (optional)
 * @param {string} options.footerText - Custom footer text (optional)
 * @param {boolean} options.showWatermark - Show watermark (optional)
 * @param {string} options.language - Output language: 'am', 'en', 'om'
 */
export const generateDailyReportPDF = async (rows, date, t, options = {}) => {
  try {
    console.log("📄 Generating Daily Report PDF...");

    if (!rows || rows.length === 0) {
      throw new Error("No data to export");
    }

    // Filter valid rows
    const validRows = rows.filter((r) => r.dept || r.service);

    if (validRows.length === 0) {
      throw new Error("No valid data to export");
    }

    // ─── 🔍 AUTO-DETECT LANGUAGE USING detectLanguage ───
    // Get sample text from first few rows for language detection
    const sampleText = validRows
      .slice(0, 5)
      .map((r) => (r.dept || "") + " " + (r.service || ""))
      .join(" ");

    const detected = detectLanguage(sampleText);
    console.log(`🔍 Detected language from content: ${detected}`);

    // Determine language: use options if provided, otherwise detect
    let lang = options?.language || "am";

    // Auto-detect if no language specified in options
    if (!options?.language) {
      if (detected === "amharic") {
        lang = "am";
        console.log(`🔍 Auto-detected Amharic content, using Amharic font`);
      } else if (detected === "english") {
        lang = "en";
        console.log(`🔍 Auto-detected English content, using English font`);
      } else if (detected === "mixed") {
        lang = "am"; // Default to Amharic for mixed content
        console.log(`🔍 Mixed content detected, defaulting to Amharic font`);
      } else {
        lang = "am"; // Default to Amharic
        console.log(`🔍 Language not detected, defaulting to Amharic`);
      }
    } else {
      console.log(`📄 Using user-specified language: ${lang.toUpperCase()}`);
    }
    // ─── END OF AUTO-DETECTION ───

    // Language-specific labels
    const LABELS = {
      am: {
        title: "ዕለታዊ ሪፖርት",
        subtitle: "የአዲስ መሶብ የአንድ ማዕከል አገልግሎት",
        reportDate: "የሪፖርቱ ቀን",
        colNo: "ቁጥር",
        colDept: "ዘርፍ",
        colService: "አገልግሎት",
        colMale: "ወንድ",
        colFemale: "ሴት",
        colTotal: "ድምር",
        grandTotal: "ጠቅላላ ድምር",
        footer: "በአዲስ መሶብ የአንድ ማዕከል አገልግሎት ማእከል የተዘጋጀ",
        generatedBy: "ገጽ",
        of: "ከ",
        page: "ገጽ",
      },
      en: {
        title: "Daily Report",
        subtitle: "A-MESOB One-Stop Service Center",
        reportDate: "Report Date",
        colNo: "#",
        colDept: "Department",
        colService: "Service",
        colMale: "Male",
        colFemale: "Female",
        colTotal: "Total",
        grandTotal: "Grand Total",
        footer: "Generated by A-MESOB One-Stop Service Center",
        generatedBy: "Page",
        of: "of",
        page: "Page",
      },
      om: {
        title: "Guyyaa Guyyaa Oduu",
        subtitle: "A-MESOB One-Stop Tajaajila",
        reportDate: "Guyyaa Oduu",
        colNo: "#",
        colDept: "Kutaa",
        colService: "Tajaajila",
        colMale: "Dhiira",
        colFemale: "Dubartii",
        colTotal: "Waliigala",
        grandTotal: "Waliigala Guutuu",
        footer: "A-MESOB One-Stop Tajaajila Keessatti Qophaa'e",
        generatedBy: "Fuula",
        of: "keessaa",
        page: "Fuula",
      },
    };

    const labels = LABELS[lang] || LABELS.am;

    // Create PDF engine with daily theme
    const engine = createPDF({
      orientation: "landscape",
      theme: "daily",
    });

    // Get the document instance
    const doc = engine.getDoc();

    // ✅ IMPORTANT: Load fonts into this document
    // (createPDF()/engine.init() already calls loadFonts() once, but this
    // is safe to call again — loadFonts() no-ops if doc.__fontsLoaded is
    // already true. Kept here for explicitness / defensive re-entry.)
    loadFonts(doc, { silent: false });

    // ─── Helper: Set font based on text content ───
    // ✅ FIXED: previously this switched the FONT NAME for bold
    // (FONT_NAMES.ethiopicBold / FONT_NAMES.latinBold) while hardcoding
    // the style argument to "normal" — so bold text asked jsPDF for
    // ("<name>-Bold", "normal"), a pair that was never registered, and
    // silently fell back to Helvetica. FONT_NAMES.ethiopic/latin now
    // resolve to the single registered family for both weights; only the
    // *style* argument should ever vary.
    const setSmartFont = (text, bold = false) => {
      try {
        const hasAmharic = isAmharic(text);
        const style = bold ? "bold" : "normal";

        if (hasAmharic) {
          // Use Ethiopic fonts if available
          if (doc.__hasEthiopicFont) {
            doc.setFont(FONT_NAMES.ethiopic, style);
          } else {
            // Fallback to helvetica with bold style
            doc.setFont("helvetica", style);
          }
        } else {
          // Use Latin fonts for English/Oromo
          if (doc.__hasLatinFont) {
            doc.setFont(FONT_NAMES.latin, style);
          } else {
            doc.setFont("helvetica", style);
          }
        }
      } catch (error) {
        console.warn("Font fallback:", error.message);
        doc.setFont("helvetica", bold ? "bold" : "normal");
      }
    };

    // ─── Set document metadata ────────────────────────────────────────────────
    try {
      doc.setProperties({
        title: labels.title,
        author: options?.author || "A-MESOB One-Stop Service Center",
        subject: options?.subject || labels.title,
        keywords: options?.keywords || "daily, report, service, Amharic",
        creator: "A-MESOB PDF Generator",
      });
    } catch (metadataError) {
      console.debug("Could not set document metadata:", metadataError.message);
    }

    // ─── Title ────────────────────────────────────────────────────────────────
    setSmartFont(labels.title, true);
    doc.setFontSize(20);
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;
    doc.text(encodeText(labels.title), pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 12;

    // ─── Subtitle ──────────────────────────────────────────────────────────────
    setSmartFont(labels.subtitle, false);
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(encodeText(labels.subtitle), pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 10;
    doc.setTextColor(0, 0, 0);

    // ─── Date ──────────────────────────────────────────────────────────────────
    const reportDate = date || new Date().toISOString().split("T")[0];
    // Format date for display
    const displayDate = reportDate.split("-").reverse().join("/");

    setSmartFont(`${labels.reportDate}: ${displayDate}`, false);
    doc.setFontSize(11);
    doc.text(
      encodeText(`${labels.reportDate}: ${displayDate}`),
      pageWidth / 2,
      yPos,
      {
        align: "center",
      },
    );
    yPos += 14;

    // ─── Draw separator line ──────────────────────────────────────────────────
    doc.setDrawColor(26, 107, 74);
    doc.setLineWidth(0.5);
    doc.line(15, yPos, pageWidth - 15, yPos);
    yPos += 10;

    // ─── Calculate Totals ─────────────────────────────────────────────────────
    const grandTotal = validRows.reduce(
      (sum, row) => sum + (row.total || 0),
      0,
    );
    const grandMale = validRows.reduce((sum, row) => sum + (row.male || 0), 0);
    const grandFemale = validRows.reduce(
      (sum, row) => sum + (row.female || 0),
      0,
    );

    // ─── Table ─────────────────────────────────────────────────────────────────
    const head = [
      [
        labels.colNo,
        labels.colDept,
        labels.colService,
        labels.colMale,
        labels.colFemale,
        labels.colTotal,
      ],
    ];

    // Build body with proper encoding
    const body = validRows.map((row, idx) => [
      `${idx + 1}`,
      encodeText(row.dept || "—"),
      encodeText(row.service || "—"),
      row.male || 0,
      row.female || 0,
      row.total || 0,
    ]);

    const foot = [
      ["", "", labels.grandTotal, grandMale, grandFemale, grandTotal],
    ];

    // ─── Import autoTable dynamically ────────────────────────────────────────
    const autoTable = (await import("jspdf-autotable")).default;

    autoTable(doc, {
      startY: yPos,
      head: head,
      body: body,
      foot: foot,
      margin: { left: 15, right: 15 },
      theme: options?.tableTheme || "striped",
      headStyles: {
        fillColor: [26, 107, 74],
        textColor: [255, 255, 255],
        fontSize: options?.headerFontSize || 10,
        fontStyle: "bold",
        halign: "center",
        valign: "middle",
        cellPadding: 5,
      },
      bodyStyles: {
        fontSize: options?.bodyFontSize || 9,
        cellPadding: 4,
        halign: "center",
        valign: "middle",
      },
      footStyles: {
        fillColor: [240, 247, 244],
        textColor: [26, 107, 74],
        fontStyle: "bold",
        fontSize: options?.footerFontSize || 10,
        halign: "center",
        valign: "middle",
      },
      columnStyles: {
        0: { cellWidth: 15, halign: "center" },
        1: { cellWidth: "auto" },
        2: { cellWidth: "auto" },
        3: { cellWidth: 25, halign: "center" },
        4: { cellWidth: 25, halign: "center" },
        5: { cellWidth: 30, halign: "center" },
      },
      // ✅ Handle mixed language content with proper fonts.
      // Only the FAMILY name needs to be chosen per-cell here — the STYLE
      // (bold for head/foot, normal for body) is already supplied by
      // headStyles/footStyles/bodyStyles above and is now honored
      // correctly because fontLoader.js registers bold under the same
      // family name as regular.
      didParseCell: (data) => {
        const cellText = String(data.cell.raw || "");
        const hasAmharic = /[\u1200-\u137F]/.test(cellText);

        if (hasAmharic) {
          data.cell.styles.font = doc.__hasEthiopicFont
            ? FONT_NAMES.ethiopic
            : "helvetica";
        } else {
          data.cell.styles.font = doc.__hasLatinFont
            ? FONT_NAMES.latin
            : "helvetica";
        }

        // Ensure proper encoding
        data.cell.raw = encodeText(cellText);
      },
      styles: {
        font: doc.__hasLatinFont ? FONT_NAMES.latin : "helvetica",
      },
      pageBreak: "auto",
      tableWidth: "auto",
    });

    // Update yPos after table
    yPos = doc.lastAutoTable?.finalY + 10 || yPos + 50;

    // ─── Add Watermark if requested ──────────────────────────────────────────
    if (options?.showWatermark) {
      try {
        const watermarkText =
          options?.watermarkText ||
          (lang === "am"
            ? "ሚስጥራዊ"
            : lang === "om"
              ? "Iccitii"
              : "Confidential");
        const pageCount = doc.internal.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          setSmartFont(watermarkText, true);
          doc.setFontSize(options?.watermarkSize || 60);
          doc.setTextColor(200, 200, 200);
          doc.text(
            encodeText(watermarkText),
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() / 2,
            {
              align: "center",
              angle: options?.watermarkAngle || -45,
            },
          );
        }
        doc.setTextColor(0, 0, 0);
      } catch (watermarkError) {
        console.warn("Watermark addition failed:", watermarkError.message);
      }
    }

    // ─── Footer ────────────────────────────────────────────────────────────────
    const footerText = options?.footerText || labels.footer;
    const pageCount = doc.internal.getNumberOfPages();
    const footerY = doc.internal.pageSize.getHeight() - 12;

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      // Draw footer line
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(15, footerY - 4, pageWidth - 15, footerY - 4);

      // Footer text
      setSmartFont(footerText, false);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(encodeText(footerText), pageWidth / 2, footerY, {
        align: "center",
      });

      // Page numbers
      // Note: reuses whatever font setSmartFont(footerText, false) just set
      // (normal weight) — the page-number label ("ገጽ 1 ከ 1") is not bold,
      // so this is correct as-is.
      doc.text(
        `${labels.page} ${i} ${labels.of} ${pageCount}`,
        pageWidth - 15,
        footerY,
        { align: "right" },
      );
    }

    // ─── Save ──────────────────────────────────────────────────────────────────
    const safeDate = reportDate.replace(/\//g, "-");
    const langSuffix = lang === "am" ? "_am" : lang === "om" ? "_om" : "_en";
    const filename =
      options?.filename || `daily_report${langSuffix}_${safeDate}.pdf`;
    engine.save(filename);

    console.log(
      `✅ Daily Report PDF generated successfully in ${lang.toUpperCase()}!`,
    );
    console.log(`📄 Saved as: ${filename}`);
    console.log(
      `📊 Total rows: ${validRows.length}, Grand total: ${grandTotal}`,
    );

    return true;
  } catch (error) {
    console.error("❌ Daily Report PDF Error:", error.message);
    console.error("Stack trace:", error.stack);
    throw error;
  }
};

export default generateDailyReportPDF;
