// components/golden-monday/ReportExport.jsx
// Export reports for Golden Monday (attendance, sessions, gallery) - PDF, Excel, Word
// ✅ FIXED: Complete table data for ALL report types with Amharic as default

import { useState, useEffect, useCallback, useRef } from "react";
import { C, F } from "../../styles/theme";
import { useLanguage } from "../../hooks/useLanguage";
import { goldenMondayAPI } from "../../services/api";
import { showToast } from "../../utils/toastHelper";
import { createPDF } from "../../utils/pdf/pdfEngine";
import { FONT_NAMES } from "../../utils/pdf/fontLoader";
import { isAmharic } from "../../utils/pdf/language";
import {
  FiDownload,
  FiFileText,
  FiCalendar,
  FiUsers,
  FiCamera,
  FiLoader,
  FiCheck,
  FiFile,
  FiMessageCircle,
  FiTrendingUp,
  FiBriefcase,
  FiCpu,
} from "react-icons/fi";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

// ── Ethiopian calendar conversion ──
const ETHIOPIAN_MONTHS_AM = [
  "መስከረም",
  "ጥቅምት",
  "ህዳር",
  "ታህሳስ",
  "ጥር",
  "የካቲት",
  "መጋቢት",
  "ሚያዝያ",
  "ግንቦት",
  "ሰኔ",
  "ሐምሌ",
  "ነሐሴ",
  "ጳጉሜ",
];

const JDN_EPOCH_OFFSET_AMETE_MIHRET = 1723856;

function gregorianToJDN(year, month, day) {
  const a = Math.floor((14 - month) / 12);
  const y = year + 4800 - a;
  const m = month + 12 * a - 3;
  return (
    day +
    Math.floor((153 * m + 2) / 5) +
    365 * y +
    Math.floor(y / 4) -
    Math.floor(y / 100) +
    Math.floor(y / 400) -
    32045
  );
}

function toEthiopianDate(date = new Date()) {
  const jdn = gregorianToJDN(
    date.getFullYear(),
    date.getMonth() + 1,
    date.getDate(),
  );
  const offsetDays = jdn - JDN_EPOCH_OFFSET_AMETE_MIHRET;
  const r = offsetDays % 1461;
  const n = (r % 365) + 365 * Math.floor(r / 1460);
  const year =
    4 * Math.floor(offsetDays / 1461) +
    Math.floor(r / 365) -
    Math.floor(r / 1460);
  const month = Math.floor(n / 30) + 1;
  const day = (n % 30) + 1;
  return { year, month, day };
}

function formatEthiopianDateAmharic(date = new Date()) {
  const { year, day, month } = toEthiopianDate(date);
  const monthName = ETHIOPIAN_MONTHS_AM[month - 1];
  return `${monthName} ${day} ቀን ${year} ዓ.ም`;
}

// ── Mixed-script text drawing ──
const AMHARIC_CHAR_RE = /[\u1200-\u137F]/;
const SCRIPT_RUN_RE = /[\u1200-\u137F]+|[^\u1200-\u137F]+/g;

function splitIntoScriptRuns(text) {
  const str = String(text ?? "");
  const runs = str.match(SCRIPT_RUN_RE) || [str];
  return runs.map((run) => ({
    text: run,
    isAmharic: AMHARIC_CHAR_RE.test(run),
  }));
}

function setFontForRun(doc, isAmharicRun, bold) {
  const style = bold ? "bold" : "normal";
  try {
    if (isAmharicRun) {
      doc.setFont(
        doc.__hasEthiopicFont ? FONT_NAMES.ethiopic : "helvetica",
        style,
      );
    } else {
      doc.setFont(doc.__hasLatinFont ? FONT_NAMES.latin : "helvetica", style);
    }
  } catch (error) {
    console.warn("Font fallback while drawing mixed text:", error.message);
    doc.setFont("helvetica", style);
  }
}

function drawMixedScriptText(doc, text, x, y, opts = {}) {
  const { align = "left", bold = false } = opts;
  const runs = splitIntoScriptRuns(text);
  const widths = runs.map((run) => {
    setFontForRun(doc, run.isAmharic, bold);
    return doc.getTextWidth(run.text);
  });
  const totalWidth = widths.reduce((sum, w) => sum + w, 0);

  let startX = x;
  if (align === "center") startX = x - totalWidth / 2;
  else if (align === "right") startX = x - totalWidth;

  let cursorX = startX;
  runs.forEach((run, i) => {
    setFontForRun(doc, run.isAmharic, bold);
    doc.text(run.text, cursorX, y, { align: "left" });
    cursorX += widths[i];
  });
  return totalWidth;
}

// ── Translation Labels (Amharic Default) ──
const getLabels = (lang = "am") => {
  const isAm = lang === "am";
  const isOm = lang === "om";

  return {
    // Common
    generated: isAm ? "የተዘጋጀው" : isOm ? "Kan qophaa'e" : "Generated",
    page: isAm ? "ገጽ" : isOm ? "Fuula" : "Page",
    of: isAm ? "ከ" : isOm ? "keessaa" : "of",
    name: isAm ? "ስም" : isOm ? "Maqaa" : "Name",
    department: isAm ? "ዘርፍ" : isOm ? "Kutaa" : "Department",
    email: isAm ? "ኢሜል" : isOm ? "Imeelii" : "Email",
    status: isAm ? "ሁኔታ" : isOm ? "Haala" : "Status",
    date: isAm ? "ቀን" : isOm ? "Guyyaa" : "Date",
    total: isAm ? "ጠቅላላ" : isOm ? "Waliigala" : "Total",
    rating: isAm ? "ደረጃ" : isOm ? "Sadarkaa" : "Rating",
    title: isAm ? "ርዕስ" : isOm ? "Mataduree" : "Title",
    category: isAm ? "ምድብ" : isOm ? "Ramaddii" : "Category",
    unknown: isAm ? "ያልታወቀ" : isOm ? "Hin beekamne" : "Unknown",
    na: isAm ? "የለም" : isOm ? "Hin jiru" : "N/A",
    untitled: isAm ? "ርዕስ የሌለው" : isOm ? "Mataduree hin qabne" : "Untitled",
    other: isAm ? "ሌላ" : isOm ? "Kaan" : "Other",
    footerText: isAm
      ? "በአዲስ መሶብ ወርቃማ ሰኞ ስርዓት የተዘጋጀ"
      : isOm
        ? "Sistimii Wiixata Warqee A-MESOB tiin qophaa'e"
        : "Generated by Addis MESOB Golden Monday System",

    // Report Types
    attendanceReport: isAm
      ? "የመገኘት ሪፖርት"
      : isOm
        ? "Gabaasa Argamaa"
        : "Attendance Report",
    sessionsReport: isAm
      ? "የክፍለ-ጊዜ ሪፖርት"
      : isOm
        ? "Gabaasa Yeroo"
        : "Sessions Report",
    galleryReport: isAm
      ? "የስዕል ማሳያ ሪፖርት"
      : isOm
        ? "Gabaasa Fakkii"
        : "Gallery Report",
    experiencesReport: isAm
      ? "የተጋሩ ተሞክሮዎች ሪፖርት"
      : isOm
        ? "Gabaasa Muuxannoo Qoodatame"
        : "Experiences Shared Report",
    resultsReport: isAm
      ? "የተገኙ ውጤቶች ሪፖርት"
      : isOm
        ? "Gabaasa Bu'aa Argame"
        : "Results Gained Report",
    performanceReport: isAm
      ? "የሰራተኞች አፈጻጸም ሪፖርት"
      : isOm
        ? "Gabaasa Hojjataa"
        : "Employee Performance Report",
    insightsReport: isAm
      ? "የዳሽቦርድ እና የAI ግንዛቤዎች ሪፖርት"
      : isOm
        ? "Gabaasa Dashboard fi Hubannoo AI"
        : "Dashboard & AI Insights Report",

    // Attendance specific
    present: isAm ? "ተገኝተዋል" : isOm ? "Argaman" : "Present",
    absent: isAm ? "አልተገኙም" : isOm ? "Hin argamne" : "Absent",
    attendanceRate: isAm
      ? "የመገኘት መጠን"
      : isOm
        ? "Hirmaanna Argamaa"
        : "Attendance Rate",
    detailedAttendance: isAm
      ? "ዝርዝር መገኘት"
      : isOm
        ? "Argama Gadifageessa"
        : "Detailed Attendance",
    signature: isAm ? "ፊርማ" : isOm ? "Mallattoo" : "Signature",
    signed: isAm ? "ተፈርሟል" : isOm ? "Mallatteeffame" : "Signed",
    notSigned: isAm ? "አልተፈረሙም" : isOm ? "Hin mallatteeffamne" : "Not Signed",
    checkedInAt: isAm ? "የገቡበት ሰዓት" : isOm ? "Yeroo Galan" : "Checked In At",
    feedback: isAm ? "አስተያየት" : isOm ? "Yaada" : "Feedback",

    // Sessions specific
    presenter: isAm ? "አቅራቢ" : isOm ? "Dhiheessituu" : "Presenter",
    attendees: isAm ? "ተሳታፊዎች" : isOm ? "Hirmaattota" : "Attendees",

    // Gallery specific
    uploadedBy: isAm ? "ያስገባው" : isOm ? "Kan fe'e" : "Uploaded By",

    // Experiences specific
    whatILearned: isAm ? "የተማርኩት" : isOm ? "Waan baradhe" : "What I Learned",
    relevanceRating: isAm ? "ተግባራዊነት" : isOm ? "Mirkanaa'ina" : "Relevance",
    wouldRecommend: isAm ? "ምክር ይሰጣሉ?" : isOm ? "Gorsa ni kennu?" : "Recommend",

    // Results specific
    whatIApplied: isAm
      ? "የተገበርኩት"
      : isOm
        ? "Waan hojii irra oolche"
        : "What I Applied",
    measurableOutcome: isAm
      ? "ሊለካ የሚችል ውጤት"
      : isOm
        ? "Bu'aa Safaruu Danda'amu"
        : "Measurable Outcome",
    outcomeCategory: isAm
      ? "የውጤት ምድብ"
      : isOm
        ? "Ramaddii Bu'aa"
        : "Outcome Category",

    // Performance specific
    employee: isAm ? "ሰራተኛ" : isOm ? "Hojjetaa" : "Employee",
    position: isAm ? "ሹመት" : isOm ? "Aangoo" : "Position",
    timesPresented: isAm
      ? "ያቀረቡት ጊዜ"
      : isOm
        ? "Yeroo Dhiheessan"
        : "Times Presented",
    avgRating: isAm
      ? "አማካይ ደረጃ"
      : isOm
        ? "Sadarkaa Giddugaleessa"
        : "Avg Rating",
    isEligible: isAm ? "ብቁ ነው" : isOm ? "Maluqaadha" : "Eligible",

    // Insights specific
    metric: isAm ? "መለኪያ" : isOm ? "Safartuu" : "Metric",
    value: isAm ? "እሴት" : isOm ? "Gatii" : "Value",
    aiSuggestions: isAm ? "የAI ምክሮች" : isOm ? "Gorsa AI" : "AI Suggestions",

    // Export controls
    reportTitle: isAm ? "ሪፖርት" : isOm ? "Gabaasa" : "Report",
    exportSuccess: isAm
      ? "ሪፖርቱ በተሳካ ሁኔታ ተዘጋጅቷል!"
      : isOm
        ? "Gabaasiin milkaa'inaan qophaa'e!"
        : "Report exported successfully!",
    exportError: isAm
      ? "ሪፖርቱን ማዘጋጀት አልተቻለም"
      : isOm
        ? "Gabaasiin qophaauu hin dandeenye"
        : "Failed to export report",
    exporting: isAm
      ? "በማዘጋጀት ላይ..."
      : isOm
        ? "Qophaa'aa jira..."
        : "Exporting...",
    exportReport: isAm
      ? "ሪፖርት ያውርዱ"
      : isOm
        ? "Gabaasa Buqqisaa"
        : "Export Report",
  };
};

export default function ReportExport({ sessionId }) {
  const { language } = useLanguage();
  const [exporting, setExporting] = useState(false);
  const [reportType, setReportType] = useState("attendance");
  const [exportFormat, setExportFormat] = useState("pdf");

  // Force Amharic as default, allow other languages
  const reportLang = language || "am";

  // Get labels based on language
  const labels = getLabels(reportLang);

  // Translation helper
  const t = (key, fallback) => {
    return labels[key] || fallback || key;
  };

  const [dateRange, setDateRange] = useState(() => {
    const now = new Date();
    const thirtyDaysAgo = new Date(now);
    thirtyDaysAgo.setDate(now.getDate() - 30);
    return {
      start: thirtyDaysAgo.toISOString().split("T")[0],
      end: now.toISOString().split("T")[0],
    };
  });

  const reportTypes = [
    {
      value: "attendance",
      label: t("attendanceReport", "Attendance Report"),
      icon: <FiUsers size={14} />,
    },
    {
      value: "sessions",
      label: t("sessionsReport", "Sessions Report"),
      icon: <FiFileText size={14} />,
    },
    {
      value: "gallery",
      label: t("galleryReport", "Gallery Report"),
      icon: <FiCamera size={14} />,
    },
    {
      value: "experiences",
      label: t("experiencesReport", "Experiences Shared"),
      icon: <FiMessageCircle size={14} />,
    },
    {
      value: "results",
      label: t("resultsReport", "Results Gained"),
      icon: <FiTrendingUp size={14} />,
    },
    {
      value: "employee-performance",
      label: t("performanceReport", "Employee Performance"),
      icon: <FiBriefcase size={14} />,
    },
    {
      value: "dashboard-insights",
      label: t("insightsReport", "Dashboard & AI Insights"),
      icon: <FiCpu size={14} />,
    },
  ];

  const formatOptions = [
    { value: "pdf", label: "PDF", icon: <FiFile size={14} /> },
    { value: "excel", label: "Excel", icon: <FiFileText size={14} /> },
    { value: "word", label: "Word", icon: <FiFileText size={14} /> },
  ];

  // ── Helper: Get report data ──
  const getReportData = async (type) => {
    switch (type) {
      case "attendance": {
        const attendanceRes = await goldenMondayAPI.getAttendance(sessionId);
        const attendanceData = attendanceRes.data.attendance || [];
        return {
          title: t("attendanceReport", "Attendance Report"),
          date: new Date().toISOString(),
          sessionId: sessionId,
          attendance: attendanceData,
          stats: {
            total: attendanceData.length,
            present: attendanceData.filter((a) => a.attended).length,
            absent: attendanceData.filter((a) => !a.attended).length,
          },
        };
      }
      case "sessions": {
        const sessionsRes = await goldenMondayAPI.getSessions();
        const sessions = sessionsRes.data || [];
        return {
          title: t("sessionsReport", "Sessions Report"),
          date: new Date().toISOString(),
          total: sessions.length,
          sessions: sessions,
        };
      }
      case "gallery": {
        const galleryRes = await goldenMondayAPI.getGallery({ limit: 1000 });
        return {
          title: t("galleryReport", "Gallery Report"),
          date: new Date().toISOString(),
          total: (galleryRes.data.photos || []).length,
          photos: galleryRes.data.photos || [],
        };
      }
      case "experiences": {
        const expRes = await goldenMondayAPI.getExperiences(
          sessionId,
          null,
          1,
          100,
        );
        return {
          title: t("experiencesReport", "Experiences Shared Report"),
          date: new Date().toISOString(),
          total: (expRes.data.experiences || []).length,
          experiences: expRes.data.experiences || [],
        };
      }
      case "results": {
        const resRes = await goldenMondayAPI.getResults(
          sessionId,
          "all",
          1,
          100,
        );
        return {
          title: t("resultsReport", "Results Gained Report"),
          date: new Date().toISOString(),
          total: (resRes.data.results || []).length,
          results: resRes.data.results || [],
        };
      }
      case "employee-performance": {
        const perfRes = await goldenMondayAPI.getEmployeePerformanceReport();
        return {
          title: t("performanceReport", "Employee Performance Report"),
          date: new Date().toISOString(),
          performance: perfRes.data.performance || [],
        };
      }
      case "dashboard-insights": {
        const insightRes = await goldenMondayAPI.getDashboardReport();
        return {
          title: t("insightsReport", "Dashboard & AI Insights Report"),
          date: new Date().toISOString(),
          ...insightRes.data,
          insights: insightRes.data.insights || [],
          metrics: insightRes.data.metrics || {},
        };
      }
      default:
        throw new Error(`Unknown report type: ${type}`);
    }
  };

  const getFilename = (type, format) => {
    const date = new Date().toISOString().split("T")[0];
    const langSuffix =
      reportLang === "am" ? "_am" : reportLang === "om" ? "_om" : "_en";
    return `golden-monday-${type}${langSuffix}_${date}.${format}`;
  };

  // ─── EXPORT AS PDF ──────────────────────────────────────────
  const exportAsPDF = async (data, filename) => {
    try {
      const autoTable = (await import("jspdf-autotable")).default;

      const engine = createPDF({ orientation: "landscape", theme: "report" });
      const doc = engine.getDoc();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Title
      doc.setFontSize(18);
      doc.setTextColor(26, 58, 173);
      drawMixedScriptText(
        doc,
        data.title || t("reportTitle", "Report"),
        pageWidth / 2,
        20,
        { align: "center", bold: true },
      );

      // Subtitle / Date
      const generatedDate = new Date(data.date);
      const ethiopianDateStr = formatEthiopianDateAmharic(generatedDate);
      const gregorianDateStr = generatedDate.toLocaleString();

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      drawMixedScriptText(
        doc,
        `${t("generated", "Generated")}: ${ethiopianDateStr}  |  ${gregorianDateStr}`,
        pageWidth / 2,
        28,
        { align: "center" },
      );

      let yPos = 35;

      // ── Helper: Create table with proper font support ──
      const createTable = (headers, rows, startY, options = {}) => {
        const {
          title = null,
          titleSize = 12,
          fontSize = 8,
          theme = "striped",
          columnStyles = {},
          rowHeight = 8,
        } = options;

        let currentY = startY;

        if (title) {
          doc.setFontSize(titleSize);
          doc.setTextColor(0, 0, 0);
          drawMixedScriptText(doc, title, 14, currentY);
          currentY += 6;
        }

        // Ensure we have enough space
        const requiredSpace = rows.length * rowHeight + 30;
        if (currentY + requiredSpace > doc.internal.pageSize.getHeight() - 40) {
          doc.addPage();
          currentY = 20;
        }

        autoTable(doc, {
          startY: currentY,
          head: [headers],
          body: rows,
          theme: theme,
          headStyles: {
            fillColor: [26, 58, 173],
            textColor: [255, 255, 255],
            fontSize: 8,
            font: doc.__hasEthiopicFont ? FONT_NAMES.ethiopic : "helvetica",
          },
          styles: {
            fontSize: fontSize,
            font: doc.__hasLatinFont ? FONT_NAMES.latin : "helvetica",
          },
          columnStyles: columnStyles,
          rowHeight: rowHeight,
          tableWidth: pageWidth - 28,
          margin: { left: 14, right: 14 },
          didParseCell: (cellData) => {
            const raw = String(cellData.cell.raw || "");
            const hasAmharic = /[\u1200-\u137F]/.test(raw);
            cellData.cell.styles.font = hasAmharic
              ? doc.__hasEthiopicFont
                ? FONT_NAMES.ethiopic
                : "helvetica"
              : doc.__hasLatinFont
                ? FONT_NAMES.latin
                : "helvetica";
          },
        });

        return doc.lastAutoTable.finalY + 6;
      };

      // ─── ATTENDANCE REPORT ──────────────────────────────────
      if (data.attendance) {
        const total = data.attendance.length;
        const present = data.attendance.filter((a) => a.attended).length;
        const absentCount = total - present;
        const rate = total > 0 ? Math.round((present / total) * 100) : 0;

        // Summary
        const summaryRows = [
          [t("total", "Total"), total],
          [t("present", "Present"), present],
          [t("absent", "Absent"), absentCount],
          [t("attendanceRate", "Attendance Rate"), `${rate}%`],
        ];

        yPos = createTable(
          [t("metric", "Metric"), t("value", "Value")],
          summaryRows,
          yPos,
          {
            title: t("attendanceReport", "Attendance Report Summary"),
            fontSize: 9,
          },
        );

        // Detailed Attendance
        const presentWithSignatures = data.attendance.filter(
          (a) => a.attended && a.signature && a.signature.length > 100,
        );
        const presentWithoutSignature = data.attendance.filter(
          (a) => a.attended && (!a.signature || a.signature.length <= 100),
        );
        const absentEmployees = data.attendance.filter((a) => !a.attended);
        const sortedAttendance = [
          ...presentWithSignatures,
          ...presentWithoutSignature,
          ...absentEmployees,
        ];

        const headers = [
          t("name", "Name"),
          t("department", "Dept"),
          t("email", "Email"),
          t("status", "Status"),
          t("signature", "Sig"),
          t("checkedInAt", "Time"),
          t("feedback", "Feedback"),
        ];

        const tableData = sortedAttendance.map((a) => {
          const status = a.attended
            ? `✅ ${t("present", "Present")}`
            : `❌ ${t("absent", "Absent")}`;
          const signatureVal =
            a.attended && a.signature && a.signature.length > 100
              ? "✓ " + t("signed", "Signed")
              : a.attended
                ? "✗ " + t("notSigned", "Not Signed")
                : "—";
          return [
            a.name || t("unknown", "Unknown"),
            a.department || t("na", "N/A"),
            a.email || t("na", "N/A"),
            status,
            signatureVal,
            a.checkedInAt
              ? new Date(a.checkedInAt).toLocaleTimeString()
              : t("na", "N/A"),
            a.feedback || "",
          ];
        });

        yPos = createTable(headers, tableData, yPos, {
          title: t("detailedAttendance", "Detailed Attendance"),
          fontSize: 7,
          rowHeight: 7,
          columnStyles: {
            0: { cellWidth: 30 },
            1: { cellWidth: 25 },
            2: { cellWidth: 35 },
            3: { cellWidth: 20 },
            4: { cellWidth: 20 },
            5: { cellWidth: 20 },
            6: { cellWidth: "auto" },
          },
        });
      }

      // ─── SESSIONS REPORT ────────────────────────────────────
      if (data.sessions) {
        const sessionData = data.sessions.map((s) => [
          s.presentationTitle || s.title || t("untitled", "Untitled"),
          new Date(s.date).toLocaleDateString(),
          s.presenterName || t("na", "N/A"),
          s.averageRating ? `${s.averageRating.toFixed(1)} ★` : t("na", "N/A"),
          s.status || t("unknown", "Unknown"),
          s.attendees?.length || 0,
        ]);

        yPos = createTable(
          [
            t("title", "Title"),
            t("date", "Date"),
            t("presenter", "Presenter"),
            t("rating", "Rating"),
            t("status", "Status"),
            t("attendees", "Attendees"),
          ],
          sessionData,
          yPos,
          {
            title: t("sessionsReport", "Sessions Report"),
            fontSize: 7,
            rowHeight: 7,
          },
        );
      }

      // ─── GALLERY REPORT ─────────────────────────────────────
      if (data.photos) {
        const galleryData = data.photos.map((p) => [
          p.title || t("untitled", "Untitled"),
          p.category || t("other", "Other"),
          new Date(p.createdAt).toLocaleDateString(),
          p.uploadedByName || t("unknown", "Unknown"),
        ]);

        yPos = createTable(
          [
            t("title", "Title"),
            t("category", "Category"),
            t("date", "Date"),
            t("uploadedBy", "Uploaded By"),
          ],
          galleryData,
          yPos,
          {
            title: t("galleryReport", "Gallery Report"),
            fontSize: 7,
            rowHeight: 7,
          },
        );
      }

      // ─── EXPERIENCES REPORT ─────────────────────────────────
      if (data.experiences) {
        const expData = data.experiences.map((e) => [
          e.userName || t("unknown", "Unknown"),
          e.department || t("na", "N/A"),
          (e.whatILearned || "").substring(0, 50) +
            ((e.whatILearned || "").length > 50 ? "..." : ""),
          `${e.relevanceRating || 0}/5`,
          e.wouldRecommend ? "✅" : "❌",
          new Date(e.createdAt).toLocaleDateString(),
        ]);

        yPos = createTable(
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("whatILearned", "What I Learned"),
            t("relevanceRating", "Rating"),
            t("wouldRecommend", "Recommend"),
            t("date", "Date"),
          ],
          expData,
          yPos,
          {
            title: t("experiencesReport", "Experiences Shared"),
            fontSize: 7,
            rowHeight: 7,
          },
        );
      }

      // ─── RESULTS REPORT ─────────────────────────────────────
      if (data.results) {
        const resData = data.results.map((r) => [
          r.userName || t("unknown", "Unknown"),
          r.department || t("na", "N/A"),
          (r.whatIApplied || "").substring(0, 40) +
            ((r.whatIApplied || "").length > 40 ? "..." : ""),
          (r.measurableOutcome || "").substring(0, 40) +
            ((r.measurableOutcome || "").length > 40 ? "..." : ""),
          r.outcomeCategory || t("other", "Other"),
          new Date(r.createdAt).toLocaleDateString(),
        ]);

        yPos = createTable(
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("whatIApplied", "What I Applied"),
            t("measurableOutcome", "Outcome"),
            t("outcomeCategory", "Category"),
            t("date", "Date"),
          ],
          resData,
          yPos,
          {
            title: t("resultsReport", "Results Gained"),
            fontSize: 7,
            rowHeight: 7,
          },
        );
      }

      // ─── EMPLOYEE PERFORMANCE REPORT ────────────────────────
      if (data.performance) {
        const perfData = data.performance.map((p) => [
          p.name || t("unknown", "Unknown"),
          p.department || t("na", "N/A"),
          p.position || t("na", "N/A"),
          p.timesPresented || 0,
          p.averageRating ? p.averageRating.toFixed(1) : t("na", "N/A"),
          p.isEligible ? "✅" : "❌",
        ]);

        yPos = createTable(
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("position", "Position"),
            t("timesPresented", "Presented"),
            t("avgRating", "Avg Rating"),
            t("isEligible", "Eligible"),
          ],
          perfData,
          yPos,
          {
            title: t("performanceReport", "Employee Performance"),
            fontSize: 7,
            rowHeight: 7,
          },
        );
      }

      // ─── DASHBOARD INSIGHTS REPORT ──────────────────────────
      if (data.insights || data.metrics) {
        // Metrics
        if (data.metrics && Object.keys(data.metrics).length > 0) {
          const metricsRows = Object.entries(data.metrics).map(([key, val]) => [
            key,
            String(val),
          ]);

          yPos = createTable(
            [t("metric", "Metric"), t("value", "Value")],
            metricsRows,
            yPos,
            {
              title: t("insightsReport", "Dashboard Metrics"),
              fontSize: 9,
              rowHeight: 7,
            },
          );
        }

        // AI Insights
        if (data.insights && data.insights.length > 0) {
          const insightRows = data.insights.map((insight) => [
            insight.title || "",
            (insight.description || "").substring(0, 60) +
              ((insight.description || "").length > 60 ? "..." : ""),
            insight.confidence
              ? `${(insight.confidence * 100).toFixed(0)}%`
              : t("na", "N/A"),
          ]);

          yPos = createTable(
            [
              t("title", "Title"),
              t("descriptionCol", "Description"),
              t("confidence", "Confidence"),
            ],
            insightRows,
            yPos,
            {
              title: t("aiSuggestions", "AI Suggestions"),
              fontSize: 7,
              rowHeight: 7,
            },
          );
        }
      }

      // ─── Footer ─────────────────────────────────────────────
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        drawMixedScriptText(
          doc,
          `${t("page", "Page")} ${i} ${t("of", "of")} ${pageCount}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: "center" },
        );
        drawMixedScriptText(
          doc,
          t("footerText", "Generated by Addis MESOB Golden Monday System"),
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 6,
          { align: "center" },
        );
      }

      engine.save(filename);
      return true;
    } catch (error) {
      console.error("PDF export error:", error);
      throw error;
    }
  };

  // ─── EXPORT AS EXCEL ────────────────────────────────────────
  const exportAsExcel = (data, filename) => {
    try {
      const wb = XLSX.utils.book_new();
      const generatedDate = new Date(data.date);
      const ethiopianDateStr = formatEthiopianDateAmharic(generatedDate);
      const gregorianDateStr = generatedDate.toLocaleString();
      const generatedRow = [
        t("generated", "Generated"),
        `${ethiopianDateStr} | ${gregorianDateStr}`,
      ];

      // ─── Attendance ──────────────────────────────────────────
      if (data.attendance) {
        const attendanceRows = [
          generatedRow,
          [],
          [
            t("name", "Name"),
            t("department", "Department"),
            t("email", "Email"),
            t("status", "Status"),
            t("signature", "Signature"),
            t("checkedInAt", "Checked In At"),
            t("feedback", "Feedback"),
          ],
        ];
        data.attendance.forEach((a) => {
          attendanceRows.push([
            a.name || t("unknown", "Unknown"),
            a.department || t("na", "N/A"),
            a.email || t("na", "N/A"),
            a.attended ? t("present", "Present") : t("absent", "Absent"),
            a.signature && a.signature.length > 100
              ? t("signed", "Signed")
              : t("notSigned", "Not Signed"),
            a.checkedInAt
              ? new Date(a.checkedInAt).toLocaleString()
              : t("na", "N/A"),
            a.feedback || "",
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(attendanceRows);
        XLSX.utils.book_append_sheet(
          wb,
          ws,
          t("attendanceReport", "Attendance"),
        );

        // Stats sheet
        const total = data.attendance.length;
        const present = data.attendance.filter((a) => a.attended).length;
        const absentCount = total - present;
        const rate = total > 0 ? Math.round((present / total) * 100) : 0;

        const statsRows = [
          [t("metric", "Metric"), t("value", "Value")],
          [t("total", "Total"), total],
          [t("present", "Present"), present],
          [t("absent", "Absent"), absentCount],
          [t("attendanceRate", "Attendance Rate"), `${rate}%`],
        ];
        const statsWs = XLSX.utils.aoa_to_sheet(statsRows);
        XLSX.utils.book_append_sheet(wb, statsWs, "Stats");
      }

      // ─── Sessions ────────────────────────────────────────────
      if (data.sessions) {
        const sessionRows = [
          generatedRow,
          [],
          [
            t("title", "Title"),
            t("date", "Date"),
            t("presenter", "Presenter"),
            t("rating", "Rating"),
            t("status", "Status"),
            t("attendees", "Attendees"),
          ],
        ];
        data.sessions.forEach((s) => {
          sessionRows.push([
            s.presentationTitle || s.title || t("untitled", "Untitled"),
            new Date(s.date).toLocaleDateString(),
            s.presenterName || t("na", "N/A"),
            s.averageRating
              ? `${s.averageRating.toFixed(1)} ★`
              : t("na", "N/A"),
            s.status || t("unknown", "Unknown"),
            s.attendees?.length || 0,
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(sessionRows);
        XLSX.utils.book_append_sheet(wb, ws, t("sessionsReport", "Sessions"));
      }

      // ─── Gallery ─────────────────────────────────────────────
      if (data.photos) {
        const galleryRows = [
          generatedRow,
          [],
          [
            t("title", "Title"),
            t("category", "Category"),
            t("date", "Date"),
            t("uploadedBy", "Uploaded By"),
          ],
        ];
        data.photos.forEach((p) => {
          galleryRows.push([
            p.title || t("untitled", "Untitled"),
            p.category || t("other", "Other"),
            new Date(p.createdAt).toLocaleDateString(),
            p.uploadedByName || t("unknown", "Unknown"),
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(galleryRows);
        XLSX.utils.book_append_sheet(wb, ws, t("galleryReport", "Gallery"));
      }

      // ─── Experiences ─────────────────────────────────────────
      if (data.experiences) {
        const expRows = [
          generatedRow,
          [],
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("whatILearned", "What I Learned"),
            t("relevanceRating", "Rating"),
            t("wouldRecommend", "Recommend"),
            t("date", "Date"),
          ],
        ];
        data.experiences.forEach((e) => {
          expRows.push([
            e.userName || t("unknown", "Unknown"),
            e.department || t("na", "N/A"),
            e.whatILearned || "",
            `${e.relevanceRating || 0}/5`,
            e.wouldRecommend ? "Yes" : "No",
            new Date(e.createdAt).toLocaleDateString(),
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(expRows);
        XLSX.utils.book_append_sheet(
          wb,
          ws,
          t("experiencesReport", "Experiences"),
        );
      }

      // ─── Results ─────────────────────────────────────────────
      if (data.results) {
        const resRows = [
          generatedRow,
          [],
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("whatIApplied", "What I Applied"),
            t("measurableOutcome", "Outcome"),
            t("outcomeCategory", "Category"),
            t("date", "Date"),
          ],
        ];
        data.results.forEach((r) => {
          resRows.push([
            r.userName || t("unknown", "Unknown"),
            r.department || t("na", "N/A"),
            r.whatIApplied || "",
            r.measurableOutcome || "",
            r.outcomeCategory || t("other", "Other"),
            new Date(r.createdAt).toLocaleDateString(),
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(resRows);
        XLSX.utils.book_append_sheet(wb, ws, t("resultsReport", "Results"));
      }

      // ─── Employee Performance ───────────────────────────────
      if (data.performance) {
        const perfRows = [
          generatedRow,
          [],
          [
            t("name", "Name"),
            t("department", "Dept"),
            t("position", "Position"),
            t("timesPresented", "Presented"),
            t("avgRating", "Avg Rating"),
            t("isEligible", "Eligible"),
          ],
        ];
        data.performance.forEach((p) => {
          perfRows.push([
            p.name || t("unknown", "Unknown"),
            p.department || t("na", "N/A"),
            p.position || t("na", "N/A"),
            p.timesPresented || 0,
            p.averageRating ? p.averageRating.toFixed(1) : t("na", "N/A"),
            p.isEligible ? "Yes" : "No",
          ]);
        });

        const ws = XLSX.utils.aoa_to_sheet(perfRows);
        XLSX.utils.book_append_sheet(
          wb,
          ws,
          t("performanceReport", "Performance"),
        );
      }

      // ─── Insights ────────────────────────────────────────────
      if (data.insights || data.metrics) {
        const insightRows = [generatedRow, []];
        if (data.metrics) {
          insightRows.push(["📊 METRICS"]);
          Object.entries(data.metrics).forEach(([key, val]) => {
            insightRows.push([key, String(val)]);
          });
          insightRows.push([]);
        }
        if (data.insights && data.insights.length > 0) {
          insightRows.push(["🤖 AI INSIGHTS"]);
          insightRows.push(["Title", "Description", "Confidence"]);
          data.insights.forEach((insight) => {
            insightRows.push([
              insight.title || "",
              insight.description || "",
              insight.confidence
                ? `${(insight.confidence * 100).toFixed(0)}%`
                : "N/A",
            ]);
          });
        }

        const ws = XLSX.utils.aoa_to_sheet(insightRows);
        XLSX.utils.book_append_sheet(wb, ws, t("insightsReport", "Insights"));
      }

      // Write file
      const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
      const blob = new Blob([wbout], { type: "application/octet-stream" });
      saveAs(blob, filename);

      return true;
    } catch (error) {
      console.error("Excel export error:", error);
      throw error;
    }
  };

  // ─── EXPORT AS WORD ──────────────────────────────────────────
  const exportAsWord = (data, filename) => {
    try {
      const ethiopianDate = formatEthiopianDateAmharic(new Date(data.date));
      const gregorianDate = new Date(data.date).toLocaleString();

      const getStatusClass = (attended) =>
        attended ? "badge-present" : "badge-absent";
      const getStatusText = (attended) =>
        attended
          ? `✅ ${t("present", "Present")}`
          : `❌ ${t("absent", "Absent")}`;

      const createTableHTML = (headers, rows, title) => {
        let html = `
          <h2>${title}</h2>
          <table>
            <tr>
              ${headers.map((h) => `<th>${h}</th>`).join("")}
            </tr>
        `;
        rows.forEach((row) => {
          html += `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`;
        });
        html += `</table>`;
        return html;
      };

      let htmlContent = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office'
              xmlns:w='urn:schemas-microsoft-com:office:word'
              xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
          <meta charset="utf-8">
          <title>${data.title || t("reportTitle", "Report")}</title>
          <!--[if gte mso 9]>
          <xml>
            <w:WordDocument>
              <w:View>Print</w:View>
              <w:Zoom>100</w:Zoom>
            </w:WordDocument>
          </xml>
          <![endif]-->
          <style>
            body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
            h1 { color: #1a3aad; border-bottom: 2px solid #1a3aad; padding-bottom: 10px; }
            h2 { color: #333; margin-top: 20px; }
            table { border-collapse: collapse; width: 100%; margin: 10px 0; }
            th { background-color: #1a3aad; color: white; padding: 8px 12px; text-align: left; }
            td { padding: 6px 12px; border: 1px solid #ddd; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .header { text-align: center; margin-bottom: 20px; }
            .footer { text-align: center; font-size: 10px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }
            .summary-box { background: #f0f4f8; padding: 15px; border-radius: 8px; margin: 10px 0; }
            .badge-present { color: green; font-weight: bold; }
            .badge-absent { color: red; font-weight: bold; }
            .signature-img { max-width: 80px; max-height: 30px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${data.title || t("reportTitle", "Report")}</h1>
            <p><strong>${t("generated", "Generated")}:</strong> ${ethiopianDate} | ${gregorianDate}</p>
          </div>
      `;

      // ─── Attendance ──────────────────────────────────────────
      if (data.attendance) {
        const total = data.attendance.length;
        const present = data.attendance.filter((a) => a.attended).length;
        const absentCount = total - present;
        const rate = total > 0 ? Math.round((present / total) * 100) : 0;

        htmlContent += `
          <h2>📊 ${t("attendanceReport", "Attendance Report")}</h2>
          <div class="summary-box">
            <table>
              <tr><td><strong>${t("total", "Total")}:</strong></td><td>${total}</td></tr>
              <tr><td><strong>${t("present", "Present")}:</strong></td><td>${present}</td></tr>
              <tr><td><strong>${t("absent", "Absent")}:</strong></td><td>${absentCount}</td></tr>
              <tr><td><strong>${t("attendanceRate", "Attendance Rate")}:</strong></td><td>${rate}%</td></tr>
            </table>
          </div>

          <h2>📋 ${t("detailedAttendance", "Detailed Attendance")}</h2>
          <table>
            <tr>
              <th>${t("name", "Name")}</th>
              <th>${t("department", "Department")}</th>
              <th>${t("email", "Email")}</th>
              <th>${t("status", "Status")}</th>
              <th>${t("signature", "Signature")}</th>
              <th>${t("checkedInAt", "Checked In")}</th>
              <th>${t("feedback", "Feedback")}</th>
            </tr>
        `;

        data.attendance.forEach((a) => {
          const statusClass = getStatusClass(a.attended);
          const statusText = getStatusText(a.attended);
          const signatureHtml =
            a.attended && a.signature && a.signature.length > 100
              ? `<img src="${a.signature}" class="signature-img" alt="Signature" />`
              : a.attended
                ? "✗ " + t("notSigned", "Not signed")
                : "—";

          htmlContent += `
            <tr>
              <td>${a.name || t("unknown", "Unknown")}</td>
              <td>${a.department || t("na", "N/A")}</td>
              <td>${a.email || t("na", "N/A")}</td>
              <td class="${statusClass}">${statusText}</td>
              <td>${signatureHtml}</td>
              <td>${a.checkedInAt ? new Date(a.checkedInAt).toLocaleString() : t("na", "N/A")}</td>
              <td>${a.feedback || ""}</td>
            </tr>
          `;
        });

        htmlContent += `</table>`;
      }

      // ─── Sessions ────────────────────────────────────────────
      if (data.sessions) {
        const headers = [
          t("title", "Title"),
          t("date", "Date"),
          t("presenter", "Presenter"),
          t("rating", "Rating"),
          t("status", "Status"),
          t("attendees", "Attendees"),
        ];
        const rows = data.sessions.map((s) => [
          s.presentationTitle || s.title || t("untitled", "Untitled"),
          new Date(s.date).toLocaleDateString(),
          s.presenterName || t("na", "N/A"),
          s.averageRating ? `${s.averageRating.toFixed(1)} ★` : t("na", "N/A"),
          s.status || t("unknown", "Unknown"),
          s.attendees?.length || 0,
        ]);
        htmlContent += createTableHTML(
          headers,
          rows,
          `📅 ${t("sessionsReport", "Sessions Report")}`,
        );
      }

      // ─── Gallery ─────────────────────────────────────────────
      if (data.photos) {
        const headers = [
          t("title", "Title"),
          t("category", "Category"),
          t("date", "Date"),
          t("uploadedBy", "Uploaded By"),
        ];
        const rows = data.photos.map((p) => [
          p.title || t("untitled", "Untitled"),
          p.category || t("other", "Other"),
          new Date(p.createdAt).toLocaleDateString(),
          p.uploadedByName || t("unknown", "Unknown"),
        ]);
        htmlContent += createTableHTML(
          headers,
          rows,
          `🖼️ ${t("galleryReport", "Gallery Report")}`,
        );
      }

      // ─── Experiences ─────────────────────────────────────────
      if (data.experiences) {
        const headers = [
          t("name", "Name"),
          t("department", "Dept"),
          t("whatILearned", "What I Learned"),
          t("relevanceRating", "Rating"),
          t("wouldRecommend", "Recommend"),
          t("date", "Date"),
        ];
        const rows = data.experiences.map((e) => [
          e.userName || t("unknown", "Unknown"),
          e.department || t("na", "N/A"),
          e.whatILearned || "",
          `${e.relevanceRating || 0}/5`,
          e.wouldRecommend ? "✅" : "❌",
          new Date(e.createdAt).toLocaleDateString(),
        ]);
        htmlContent += createTableHTML(
          headers,
          rows,
          `💡 ${t("experiencesReport", "Experiences Shared")}`,
        );
      }

      // ─── Results ─────────────────────────────────────────────
      if (data.results) {
        const headers = [
          t("name", "Name"),
          t("department", "Dept"),
          t("whatIApplied", "What I Applied"),
          t("measurableOutcome", "Outcome"),
          t("outcomeCategory", "Category"),
          t("date", "Date"),
        ];
        const rows = data.results.map((r) => [
          r.userName || t("unknown", "Unknown"),
          r.department || t("na", "N/A"),
          r.whatIApplied || "",
          r.measurableOutcome || "",
          r.outcomeCategory || t("other", "Other"),
          new Date(r.createdAt).toLocaleDateString(),
        ]);
        htmlContent += createTableHTML(
          headers,
          rows,
          `📈 ${t("resultsReport", "Results Gained")}`,
        );
      }

      // ─── Employee Performance ───────────────────────────────
      if (data.performance) {
        const headers = [
          t("name", "Name"),
          t("department", "Dept"),
          t("position", "Position"),
          t("timesPresented", "Presented"),
          t("avgRating", "Avg Rating"),
          t("isEligible", "Eligible"),
        ];
        const rows = data.performance.map((p) => [
          p.name || t("unknown", "Unknown"),
          p.department || t("na", "N/A"),
          p.position || t("na", "N/A"),
          p.timesPresented || 0,
          p.averageRating ? p.averageRating.toFixed(1) : t("na", "N/A"),
          p.isEligible ? "✅" : "❌",
        ]);
        htmlContent += createTableHTML(
          headers,
          rows,
          `👔 ${t("performanceReport", "Employee Performance")}`,
        );
      }

      // ─── Insights ────────────────────────────────────────────
      if (data.insights || data.metrics) {
        htmlContent += `<h2>🤖 ${t("insightsReport", "Dashboard & AI Insights")}</h2>`;

        if (data.metrics && Object.keys(data.metrics).length > 0) {
          htmlContent += `<h3>📊 ${t("metric", "Metrics")}</h3><table>`;
          Object.entries(data.metrics).forEach(([key, val]) => {
            htmlContent += `<tr><td><strong>${key}</strong></td><td>${val}</td></tr>`;
          });
          htmlContent += `</table>`;
        }

        if (data.insights && data.insights.length > 0) {
          htmlContent += `<h3>🤖 ${t("aiSuggestions", "AI Suggestions")}</h3><table>`;
          htmlContent += `<tr><th>${t("title", "Title")}</th><th>${t("descriptionCol", "Description")}</th><th>${t("confidence", "Confidence")}</th></tr>`;
          data.insights.forEach((insight) => {
            htmlContent += `<tr>
              <td>${insight.title || ""}</td>
              <td>${insight.description || ""}</td>
              <td>${insight.confidence ? `${(insight.confidence * 100).toFixed(0)}%` : "N/A"}</td>
            </tr>`;
          });
          htmlContent += `</table>`;
        }
      }

      // ─── Footer ──────────────────────────────────────────────
      htmlContent += `
          <div class="footer">
            <p>${t("footerText", "Generated by Addis MESOB Golden Monday System")} • ${new Date().toLocaleString()}</p>
          </div>
        </body>
        </html>
      `;

      const blob = new Blob([htmlContent], {
        type: "application/msword;charset=utf-8",
      });
      saveAs(blob, filename);
      return true;
    } catch (error) {
      console.error("Word export error:", error);
      throw error;
    }
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      const data = await getReportData(reportType);
      const filename = getFilename(reportType, exportFormat);

      let success = false;
      switch (exportFormat) {
        case "pdf":
          success = await exportAsPDF(data, filename);
          break;
        case "excel":
          success = exportAsExcel(data, filename);
          break;
        case "word":
          success = exportAsWord(data, filename);
          break;
        default:
          throw new Error(`Unknown format: ${exportFormat}`);
      }

      if (success) {
        showToast(
          `${t("exportSuccess", "Report exported successfully!")} (${exportFormat.toUpperCase()})`,
          "success",
        );
      }
    } catch (error) {
      console.error("Export failed:", error);
      showToast(
        `${t("exportError", "Failed to export report")} (${exportFormat.toUpperCase()})`,
        "error",
      );
    } finally {
      setExporting(false);
    }
  };

  return (
    <div style={{ fontFamily: F.sans }}>
      {/* Report Type Selection */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
          gap: 12,
          marginBottom: 16,
        }}
      >
        {reportTypes.map((type) => (
          <button
            key={type.value}
            onClick={() => setReportType(type.value)}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              padding: "10px 16px",
              borderRadius: 8,
              border: `2px solid ${reportType === type.value ? C.primary : C.border}`,
              background:
                reportType === type.value ? C.primary + "11" : C.white,
              color: reportType === type.value ? C.primary : C.muted,
              cursor: "pointer",
              fontSize: 13,
              fontWeight: reportType === type.value ? 600 : 400,
              transition: "all 0.2s ease",
              fontFamily: F.sans,
            }}
            aria-label={type.label}
          >
            {type.icon}
            {type.label}
            {reportType === type.value && (
              <FiCheck
                size={14}
                color={C.primary}
                style={{ marginLeft: "auto" }}
              />
            )}
          </button>
        ))}
      </div>

      {/* Export Format & Controls */}
      <div
        style={{
          display: "flex",
          flexDirection: "row",
          flexWrap: "wrap",
          gap: 10,
          alignItems: "center",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <FiCalendar size={14} color={C.muted} />
          <input
            type="date"
            value={dateRange.start}
            onChange={(e) =>
              setDateRange((prev) => ({ ...prev, start: e.target.value }))
            }
            style={{
              padding: "6px 10px",
              border: `1px solid ${C.border}`,
              borderRadius: 6,
              fontSize: 12,
              outline: "none",
              fontFamily: F.sans,
            }}
            aria-label="Start date"
          />
          <span style={{ color: C.muted }}>to</span>
          <input
            type="date"
            value={dateRange.end}
            onChange={(e) =>
              setDateRange((prev) => ({ ...prev, end: e.target.value }))
            }
            style={{
              padding: "6px 10px",
              border: `1px solid ${C.border}`,
              borderRadius: 6,
              fontSize: 12,
              outline: "none",
              fontFamily: F.sans,
            }}
            aria-label="End date"
          />
        </div>

        <div style={{ display: "flex", gap: 6 }}>
          {formatOptions.map((format) => (
            <button
              key={format.value}
              onClick={() => setExportFormat(format.value)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 4,
                padding: "6px 12px",
                borderRadius: 6,
                border: `2px solid ${exportFormat === format.value ? C.primary : C.border}`,
                background:
                  exportFormat === format.value ? C.primary : "transparent",
                color: exportFormat === format.value ? "#fff" : C.muted,
                cursor: "pointer",
                fontSize: 12,
                fontWeight: exportFormat === format.value ? 600 : 400,
                fontFamily: F.sans,
                transition: "all 0.2s ease",
              }}
            >
              {format.icon}
              {format.label}
            </button>
          ))}
        </div>

        <button
          onClick={handleExport}
          disabled={exporting}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            padding: "8px 20px",
            background: C.primary,
            color: "#fff",
            border: "none",
            borderRadius: 8,
            cursor: exporting ? "not-allowed" : "pointer",
            fontWeight: 600,
            fontSize: 13,
            fontFamily: F.sans,
            opacity: exporting ? 0.6 : 1,
            transition: "all 0.2s ease",
          }}
          aria-label="Export Report"
        >
          {exporting ? (
            <>
              <FiLoader
                size={16}
                style={{ animation: "spin 1s linear infinite" }}
              />
              {t("exporting", "Exporting...")}
            </>
          ) : (
            <>
              <FiDownload size={16} />
              {t("exportReport", "Export Report")}
            </>
          )}
        </button>
      </div>

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
