export const CRITERIA = [
  {
    id: 1,
    key: "c1",
    weight: 25,
    color: "#1a6b4a",
    titleEn: "Effective Service Delivery",
    items: [
      { text: "የቡድኑ አባላት ተጨባጭ ዉጤት ያስመዘገቡ", points: 4 },
      { text: "ሰርተው ጥቅምን ለማግኘት የሚተጉ", points: 3 },
      { text: "ያልቆራረጠ አፈጻጸም ያሳዩ", points: 3 },
      { text: "ብልሹ አሰራርን ታግለዋል", points: 4 },
      { text: "ምርጥ ፈጻሚዎች በጎ ተጽዕኖ ፈጥረዋል", points: 3 },
      { text: "ቀሪ ሥራዎችን ለመፈፀም ክህሎት ተምስክሯል", points: 4 },
      { text: "አደገኛ አዝማሚያዎች ፈትተዋል", points: 4 },
    ],
  },
  {
    id: 2,
    key: "c2",
    weight: 22,
    color: "#1e4d8c",
    titleEn: "Strong Work Ethics",
    items: [
      { text: "ሥራ የሚበድሉትን ወደ መስመር ያስገቡ", points: 9 },
      { text: "ጠንካራ የሥራ መንፈስ ያሳዩ", points: 9 },
      { text: "የአገልጋይነት መንፈስ ያዳበሩ", points: 4 },
    ],
  },
  {
    id: 3,
    key: "c3",
    weight: 23,
    color: "#7b2d8b",
    titleEn: "Timely & Quality Execution",
    items: [
      { text: "ራዕይና ተልዕኮ ጠንቅቀው ያውቃሉ", points: 4 },
      { text: "ከተማዋን ለማሻሻል የሚጥሩ", points: 3 },
      { text: "የፖሊሲዎች እምነት ያላቸዉ", points: 4 },
      { text: "ግልፅና ተገቢ አቋም ያላቸው", points: 3 },
      { text: "ተጨባጭ ለውጥ ያመጡ", points: 4 },
      { text: "ሥራ በጥራት፣ ፍጥነት ፈጽሟል", points: 5 },
    ],
  },
  {
    id: 4,
    key: "c4",
    weight: 15,
    color: "#c25a00",
    titleEn: "Creating Exemplary Work",
    items: [
      { text: "አዳዲስ ሀሳቦችን ተግባር አድርገዋል", points: 7 },
      { text: "ሁሉም ሀሳብ ነፃነት ይቀርብበት አደረጃጀት", points: 4 },
      { text: "ዘመናዊ ቴክኖሎጅ ተጠቅመዋል", points: 4 },
    ],
  },
  {
    id: 5,
    key: "c5",
    weight: 15,
    color: "#8b1a1a",
    titleEn: "Principle-Based Cooperation",
    items: [
      { text: "ተልዕኮ ማዕከል ያደረገ መደጋገፍ", points: 5 },
      { text: "ጥንካሬ/ድክመት ለቀጣዩ ተጠቀሙ", points: 4 },
      { text: "ተጠያቂነት ስርዓት ተፈጸሟል", points: 4 },
      { text: "የታታሪ ሠራተኛ መረጃ ለሥራ ዋሉ", points: 2 },
    ],
  },
];
