// src/constants/dashboard.js
export const dashboardTranslations = {
  en: {
    greetingMorning: "🌅 Good morning",
    greetingAfternoon: "☀️ Good afternoon",
    greetingEvening: "🌙 Good evening",
    welcomeMessage: "{greeting}, {userName}!",
    roleSuperAdmin: "Super Admin",
    roleAdmin: "Admin",
    roleTeamLeader: "Team Leader",
    roleEmployee: "Employee",
    lastLogin: "Last login: {date}",
    todayServices: "Today's Services",
    male: "Male",
    female: "Female",
    departments: "Departments",
    totalPresented: "Presentations",
    avgRating: "Avg Rating",
    weeklyTrend: "Weekly Trend",
    last7Days: "Last 7 days",
    deptDistribution: "Department Distribution",
    topDepts: "Top departments",
    deptPerformance: "Department Performance",
    byValue: "By value",
    distribution: "Distribution",
    byDept: "By department",
    deptReport: "Daily Department Report",
    forumAgendas: "Standing Forum Agendas",
    quickStats: "Quick Stats",
    totalServices: "Total Services",
    totalDepts: "Departments",
    goldenSessions: "Golden Sessions",
    presenters: "Presenters",
    criteriaOverview: "Evaluation Criteria Overview",
    subCriteria: "sub-criteria",
    deptName: "{name} Department",
    total: "Total",
    maleLabel: "Male",
    femaleLabel: "Female",
    chartTitle: "Department Performance",
    departmentBreakdown: "Department Breakdown",
    trend: "Trend",
    stats: "Stats",
  },
  am: {
    greetingMorning: "🌅 እንደምን አደሩ",
    greetingAfternoon: "☀️ እንደምን ቀኑ",
    greetingEvening: "🌙 እንደምን አመሹ",
    welcomeMessage: "{greeting}, {userName}!",
    roleSuperAdmin: "ልዕለ አስተዳዳሪ",
    roleAdmin: "አስተዳዳሪ",
    roleTeamLeader: "የቡድን መሪ",
    roleEmployee: "ሰራተኛ",
    lastLogin: "የመጨረሻ ግባት: {date}",
    todayServices: "ዛሬ አገልግሎቶች",
    male: "ወንድ",
    female: "ሴት",
    departments: "ዘርፎች",
    totalPresented: "አቀራረቦች",
    avgRating: "አማካይ ደረጃ",
    weeklyTrend: "ሳምንታዊ አዝማሚያ",
    last7Days: "የመጨረሻ 7 ቀናት",
    deptDistribution: "የዘርፍ ስርጭት",
    topDepts: "ከፍተኛ ዘርፎች",
    deptPerformance: "የዘርፍ አፈጻጸም",
    byValue: "በዋጋ",
    distribution: "ስርጭት",
    byDept: "በዘርፍ",
    deptReport: "ዕለታዊ ዘርፍ ሪፖርት",
    forumAgendas: "ቋሚ የመድረክ አጀንዳዎች",
    quickStats: "ፈጣን ስታቲስቲክስ",
    totalServices: "ጠቅላላ አገልግሎቶች",
    totalDepts: "ዘርፎች",
    goldenSessions: "ወርቃማ ክፍለ ጊዜዎች",
    presenters: "አቅራቢዎች",
    criteriaOverview: "የምዘና መስፈርቶች አጠቃላይ እይታ",
    subCriteria: "ንዑስ መስፈርቶች",
    deptName: "የ{name} ዘርፍ",
    total: "ጠቅላላ",
    maleLabel: "ወንድ",
    femaleLabel: "ሴት",
    chartTitle: "የዘርፍ አፈጻጸም",
    departmentBreakdown: "የዘርፍ ክፍፍል",
    trend: "አዝማሚያ",
    stats: "ስታቲስቲክስ",
  },
  om: {
    greetingMorning: "🌅 Akkam bulte",
    greetingAfternoon: "☀️ Akkam oolte",
    greetingEvening: "🌙 Akkam galgaltu",
    welcomeMessage: "{greeting}, {userName}!",
    roleSuperAdmin: "Bulchaa Ol Aanaa",
    roleAdmin: "Bulchaa",
    roleTeamLeader: "Hoogganaa Garee",
    roleEmployee: "Hojjataa",
    lastLogin: "Galmaan dhumaa: {date}",
    todayServices: "Tajaajiloota Har'aa",
    male: "Dhiira",
    female: "Dubartii",
    departments: "Kutaa",
    totalPresented: "Dhiheessawwan",
    avgRating: "Sadarkaa Giddugaleessaa",
    weeklyTrend: "Mijaa'uu Torbanii",
    last7Days: "Guyyaa 7 darban",
    deptDistribution: "Qoodima Kutaa",
    topDepts: "Kutaa Olaanaa",
    deptPerformance: "Hoji Kutaa",
    byValue: "Gatidhaan",
    distribution: "Qoodima",
    byDept: "Kutaadhaan",
    deptReport: "Gabaasa Kutaa Guyyaa",
    forumAgendas: "Ajandaa Fooraamii Dhaabbataa",
    quickStats: "Staatistiksii Dafaa",
    totalServices: "Tajaajiloota Waliigalaa",
    totalDepts: "Kutaa",
    goldenSessions: "Kutaa Warqee",
    presenters: "Dhiheessitoota",
    criteriaOverview: "Ilaalcha Waliigalaa Madaallii",
    subCriteria: "madaallii xiqqoo",
    deptName: "Kutaa {name}",
    total: "Waliigala",
    maleLabel: "Dhiira",
    femaleLabel: "Dubartii",
    chartTitle: "Hoji Kutaa",
    departmentBreakdown: "Qoodima Kutaa",
    trend: "Mijaa'uu",
    stats: "Staatistiksii",
  },
};
