export const SERVICES = [
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ቲን ሬጅስትሬሽን",
    nameEn: "TIN Registration",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "አዲስ የንግድ ፍቃድ",
    nameEn: "New Business License",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ፍቃድ ዕድሳት",
    nameEn: "Business License Renewal",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ንግድ ምዝገባ ማሻሻያ",
    nameEn: "Trade Reg. Amendment",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ምዝገባ ምትክ",
    nameEn: "Trade Reg. Replacement",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "የአሽከርካሪ ፈቃድ ዕድሳት",
    nameEn: "Driver License Renewal",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ዓመታዊ ቴክ. ምርመራ",
    nameEn: "Annual Vehicle Inspection",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የልደት ምዝገባ",
    nameEn: "Birth Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "ወሳኝ ኩነት ማረጋገጥ",
    nameEn: "Vital Events Verification",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የነዋሪነት መታወቂያ",
    nameEn: "Resident ID",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "አዲስ የኢንቨስትመንት ፍቃድ",
    nameEn: "New Investment License",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "ስራ ፈላጊዎች ምዝገባ",
    nameEn: "Jobseeker Registration",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "መረጃ፣ ምክርና ግንዛቤ",
    nameEn: "Info & Counseling",
    active: true,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "የቤት ኪራይ ውል ማደስ",
    nameEn: "Rental Contract Renewal",
    active: true,
  },
];
