// backend/src/constants/services.js
// Full service list from Addis MESOB Service Catalogue
// Shared between seed script and controller

const SERVICES = [
  // ─── 1. ገቢዎች / Revenue ───────────────────────────────────
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ቲን ሬጅስትሬሽን",
    nameEn: "TIN Registration",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "አዲስ ንግድ ምዝገባ",
    nameEn: "New Trade Registration",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "አዲስ የንግድ ሥራ ፍቃድ",
    nameEn: "New Business License",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ስም ምዝገባ",
    nameEn: "Trade Name Registration",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ፍቃድ ዕድሳት",
    nameEn: "Business License Renewal",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ንግድ ምዝገባ ማሻሻያ",
    nameEn: "Trade Reg. Amendment",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ንግድ ፍቃድ ማሻሻያ",
    nameEn: "Business License Amendment",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ምዝገባ ምትክ",
    nameEn: "Trade Reg. Replacement",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ሥራ ፈቃድ ምትክ",
    nameEn: "Business License Replacement",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "የንግድ ሥራ ፈቃድ ስረዛ",
    nameEn: "Business License Cancellation",
    active: true,
  },
  {
    dept: "ገቢዎች",
    deptEn: "Revenue",
    name: "ኢ ፋይሊንግ እና ኢ ፔይመንት ፓስወርድ",
    nameEn: "E-Filing & E-Payment Password",
    active: true,
  },

  // ─── 2. ንግድ / Trade ──────────────────────────────────────
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የግለሰብ ቅድመ አካውንት ማፅደቅ",
    nameEn: "Individual Pre-Account Approval",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የማህበራት ቅድመ አካውንት ማፅደቅ",
    nameEn: "Association Pre-Account Approval",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "አዲስ ንግድ ምዝገባ",
    nameEn: "New Trade Registration",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "አዲስ የንግድ ሥራ ፍቃድ",
    nameEn: "New Business License",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ስም ምዝገባና ማጣሪያ",
    nameEn: "Trade Name Registration & Search",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "አዲስ ንግድ ምዝገባና አዲስ የንግድ ሥራ ፍቃድ",
    nameEn: "New Trade Registration & License",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "አዲስ የድርጅት ስም",
    nameEn: "New Organization Name",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ፍቃድ ዕድሳት",
    nameEn: "Business License Renewal",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "ንግድ ምዝገባ ማሻሻያ",
    nameEn: "Trade Reg. Amendment",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "ንግድ ፍቃድ ማሻሻያ",
    nameEn: "Business License Amendment",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ስም ማሻሻያ",
    nameEn: "Trade Name Amendment",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ምዝገባ ምትክ",
    nameEn: "Trade Reg. Replacement",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ሥራ ፈቃድ ምትክ",
    nameEn: "Business License Replacement",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ስም ምትክ",
    nameEn: "Trade Name Replacement",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ምዝገባ ስረዛ",
    nameEn: "Trade Reg. Cancellation",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ሥራ ፈቃድ ስረዛ",
    nameEn: "Business License Cancellation",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "የንግድ ስም ስረዛ",
    nameEn: "Trade Name Cancellation",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "Online System (16 services)",
    nameEn: "Online System Services",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "Approval - E-trade",
    nameEn: "E-Trade Approval",
    active: true,
  },
  {
    dept: "ንግድ",
    deptEn: "Trade",
    name: "በአካል መጥቶ የተስተናገደ",
    nameEn: "In-Person Service",
    active: true,
  },

  // ─── 3. አሽ/ተሽ / Driver & Vehicle Authority ───────────────
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "የአሽከርካሪ ፈቃድ ዕድሳት",
    nameEn: "Driver License Renewal",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ዓመታዊ ቴክ. ምርመራ (ቦሎ)",
    nameEn: "Annual Vehicle Inspection",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "የውጭ መንጃ ፈቃድ ቅያሪ",
    nameEn: "Foreign License Exchange",
    active: false,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ዕዳ ዕገዳ አገልግሎት",
    nameEn: "Debt Block Service",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ዕግድ ማንሳት አገልግሎት",
    nameEn: "Lift Block Service",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "የተበላሸ ምትክ መስጠት",
    nameEn: "Damaged License Replacement",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ወደውጭ የሚሄዱ አሽከርካሪዎች የአሽከርካሪነት ብቃት ማረጋገጫ",
    nameEn: "International Driving Permit",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "በተበላሸ ቦሎ ምትክ መስጠት",
    nameEn: "Damaged Inspection Certificate Replacement",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "በጠፋ ቦሎ ምትክ መስጠት",
    nameEn: "Lost Inspection Certificate Replacement",
    active: true,
  },
  {
    dept: "አሽ/ተሽ",
    deptEn: "Transport",
    name: "ቀረጥ ማንሳት አገልግሎት",
    nameEn: "Tax Removal Service",
    active: true,
  },

  // ─── 4. ትራፊክ ማኔጅምንት / Traffic Management ─────────────
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "ከአደጋ ነፃ መረጃ መስጠት",
    nameEn: "Accident-Free Record",
    active: true,
  },
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "የደንብ ተላላፊ ሪከርድ ማጣራት",
    nameEn: "Offender Record Inquiry",
    active: true,
  },
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "የተሃድሶ ስልጠና ማስተላለፍ",
    nameEn: "Rehabilitation Training Referral",
    active: true,
  },
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "ለኤምባሲ የአደጋ ሪከርድ ማረጋገጫ",
    nameEn: "Embassy Accident Record Confirmation",
    active: false,
  },
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "የጠፋ ሰሌዳ እና የአሽከርካሪነት ብቃት ማረጋገጫ",
    nameEn: "Lost License Plate & License Replacement",
    active: true,
  },
  {
    dept: "ትራፊክ",
    deptEn: "Traffic",
    name: "ለውጪ ሃገር/ለኤምባሲ የአደጋ ረከርድ ማረጋገጫ",
    nameEn: "Embassy Accident Record Certification",
    active: true,
  },

  // ─── 5. ኢንቨስትመንት / Investment Commission ────────────────
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "አዲስ የኢንቨስትመንት ፍቃድ",
    nameEn: "New Investment License",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የኢንቨስትመንት ፍቃድ ዕድሳት",
    nameEn: "Investment License Renewal",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የኢንቨስትመንት ፍቃድ ማሻሻያ",
    nameEn: "Investment License Amendment",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የኢንቨስትመንት ፍቃድ ምትክ",
    nameEn: "Investment License Replacement",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የኢንቨስትመንት ማስፋፊያ ፈቃድ",
    nameEn: "Investment Expansion License",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የኢንቨስትመንት ፍቃድ ስረዛ",
    nameEn: "Investment License Cancellation",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የግንባታ ዕቃ ቀረጥ ነፃ",
    nameEn: "Construction Material Tax Exemption",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የካፒታል ዕቃ ቀረጥ ነፃ",
    nameEn: "Capital Goods Tax Exemption",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የተሸከርካሪ ቀረጥ ነፃ",
    nameEn: "Vehicle Tax Exemption",
    active: true,
  },
  {
    dept: "ኢንቨስትመንት",
    deptEn: "Investment",
    name: "የመለዋወጫ ቀረጥ ነፃ",
    nameEn: "Spare Parts Tax Exemption",
    active: true,
  },

  // ─── 6. ሲቪል ምዝገባ / Civil Registration ──────────────────
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የልደት ምዝገባ",
    nameEn: "Birth Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የጋብቻ ምዝገባ",
    nameEn: "Marriage Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የፍቺ ምዝገባ",
    nameEn: "Divorce Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የሞት ምዝገባ",
    nameEn: "Death Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "ወሳኝ ኩነት ማረጋገጥ",
    nameEn: "Vital Events Verification",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የነዋሪነት መታወቂያ እርማት/ዕድሳት",
    nameEn: "Resident ID Correction/Renewal",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "ያላገባ ማስረጃ",
    nameEn: "Single Status Certificate",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የብሄራዊ መታወቂያ ምዝገባ",
    nameEn: "National ID Registration",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የልደት ምዝገባ ማስረጃ ግልባጭ/እርማት",
    nameEn: "Birth Certificate Copy/Correction",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የጋብቻ ምዝገባ ማስረጃ ግልባጭ/እርማት",
    nameEn: "Marriage Certificate Copy/Correction",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የፍቺ ምዝገባ ማስረጃ ግልባጭ/እርማት",
    nameEn: "Divorce Certificate Copy/Correction",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የሞት ምዝገባ ማስረጃ ግልባጭ/እርማት",
    nameEn: "Death Certificate Copy/Correction",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "ያላገባ ማስረጃ እርማት/እድሳት",
    nameEn: "Single Status Certificate Correction/Renewal",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "ያላገባ ማስረጃ ማመሳከር",
    nameEn: "Single Status Certificate Verification",
    active: true,
  },
  {
    dept: "ሲቪል ምዝገባ",
    deptEn: "Civil Registry",
    name: "የነዋሪነት መታወቂያ ማመሳከር",
    nameEn: "Residence ID Verification",
    active: true,
  },

  // ─── 7. ስራና ክህሎት / Labor & Skills Bureau ───────────────
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "ስራ ፈላጊዎች ምዝገባ",
    nameEn: "Jobseeker Registration",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "መረጃ፣ ምክርና ግንዛቤ",
    nameEn: "Info, Counseling & Awareness",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "ኢንተርፕራይዝ ማደራጀትና ወደ ስራ ማስገባት",
    nameEn: "Enterprise Organization & Employment",
    active: false,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የተደራጁ ኢንተርፕራይዞችን ወደ ስራ ማስገባት",
    nameEn: "Organized Enterprise Employment",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የአገር ውስጥ ሥራና ሠራተኛ ለሚያገናኙ ኤጀንሲዎች የብቃት ማረጋገጫ ፈቃድ",
    nameEn: "Employment Agency License",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የአገር ውስጥ ሥራና ሠራተኛ ለሚያገናኙ ኤጀንሲዎች የብቃት ማረጋገጫ ዕድሳት",
    nameEn: "Employment Agency License Renewal",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የኮንስትራክሽን ሠራተኛ ውል ማፅደቅ",
    nameEn: "Construction Labor Contract Approval",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የፋይናንስ ድጋፍ ማመቻቸት",
    nameEn: "Financial Support Facilitation",
    active: true,
  },
  {
    dept: "ስራና ክህሎት",
    deptEn: "Labor & Skills",
    name: "የካፒታል ሊዝ ድጋፍ ማመቻቸት",
    nameEn: "Capital Lease Facilitation",
    active: true,
  },

  // ─── 8. ቤቶች / Housing Development & Administration ──────
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "የቤት ኪራይ ውል ማደስ/ማቋረጥ",
    nameEn: "Rental Contract Renewal/Termination",
    active: true,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "አዲስ ውል የማዋዋል አገልግሎት",
    nameEn: "New Rental Contract Service",
    active: false,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "የቤት ቅይይር ጥያቄ",
    nameEn: "House Exchange Request",
    active: false,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "ተነሺዎች ምትክ ቤት",
    nameEn: "Displaced Persons Replacement House",
    active: false,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "የአከራይ ተከራይ ምዝገባ",
    nameEn: "Rental Registration",
    active: true,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "አምስት አመት የሞሊቸዉ የጋራ መኖሪያ ቤቶች ማስረጃ",
    nameEn: "5-Year Condominium Certificate",
    active: true,
  },
  {
    dept: "ቤቶች",
    deptEn: "Housing",
    name: "የውሃና የመብራት ማስገባት ፍቃድ",
    nameEn: "Water & Electricity Installation Permit",
    active: true,
  },

  // ─── 9. ቤቶች ልማት ኮርፖሬሽን / Housing Development Corp ────
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "የጋራ መኖሪያ ቤት በሽያጭ ማስተላለፍ",
    nameEn: "Condominium Sale Transfer",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "ቅጽ-03 የወስዱ",
    nameEn: "Form-03 Issuance",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "ቅጽ-09 የወስዱ",
    nameEn: "Form-09 Issuance",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "ቅድመ ሁኔታ መረጃ የወሰዱ",
    nameEn: "Pre-Condition Information",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "የሽያጭ ውል የተዋዋሉ",
    nameEn: "Sales Contract Agreement",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "የታተመ ቁልፍ ወረቀት",
    nameEn: "Printed Key Document",
    active: true,
  },
  {
    dept: "ቤቶች ልማት ኮርፕ",
    deptEn: "Housing Development Corp",
    name: "የንግድ ቤቶችን በጨረታ ሽያጭ ማስተላለፍ",
    nameEn: "Commercial Building Auction Sale",
    active: true,
  },

  // ─── 10. ፕላንና ልማት / Planning & Development Bureau ───────
  {
    dept: "ፕላን",
    deptEn: "Planning",
    name: "የፕላን ስምምነት መረጃ",
    nameEn: "Plan Agreement Information",
    active: true,
  },
  {
    dept: "ፕላን",
    deptEn: "Planning",
    name: "የውስጥ ለውስጥ መንገድ ጥናት",
    nameEn: "Internal Road Study",
    active: true,
  },
  {
    dept: "ፕላን",
    deptEn: "Planning",
    name: "የፕላን መረጃዎች ማሰራጨት",
    nameEn: "Plan Information Distribution",
    active: true,
  },

  // ─── 11. ግንባታ ፈቃድ / Construction Permit Authority ───────
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "አዲስ ግንባታ ፈቃድ",
    nameEn: "New Construction Permit",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የግንባታ ፈቃድ ዕድሳት",
    nameEn: "Construction Permit Renewal",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የፕላን ማሻሻያ ፈቃድ",
    nameEn: "Plan Amendment Permit",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የነባር ግንባታ ፈቃድ (As-Built)",
    nameEn: "As-Built Construction Permit",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የስም ወይም የአገልግሎት ለውጥ ፈቃድ",
    nameEn: "Name or Service Change Permit",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የህንፃ መጠቀሚያ ፈቃድ",
    nameEn: "Building Usage Permit",
    active: true,
  },
  {
    dept: "ግንባታ",
    deptEn: "Construction",
    name: "የውጭ ማስታወቂያ ፈቃድ",
    nameEn: "Outdoor Advertising Permit",
    active: true,
  },

  // ─── 12. መሬት / Land Development & Management ──────────────
  {
    dept: "መሬት",
    deptEn: "Land",
    name: "የመሬት ይዞታ ምዝገባ",
    nameEn: "Land Holding Registration",
    active: true,
  },
  {
    dept: "መሬት",
    deptEn: "Land",
    name: "የካርታ አገልግሎት",
    nameEn: "Land Map/Carta Service",
    active: true,
  },

  // ─── 13. ኢትዮ ፖስት / Ethio Post ────────────────────────────
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "ናሽናል አይዲ ቀጠሮ ማስያዝ",
    nameEn: "National ID Appointment Booking",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "ናሽናል አይዲ ህትመት",
    nameEn: "National ID Printing",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "ናሽናል አይዲ ማደል",
    nameEn: "National ID Renewal",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "ናሽናል አይዲ ምዝገባ",
    nameEn: "National ID Registration",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "ናሽናል አይዲ ማስተካከያ",
    nameEn: "National ID Correction",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "መንገድ ፈንድ",
    nameEn: "Road Fund",
    active: true,
  },
  {
    dept: "ኢትዮ ፖስት",
    deptEn: "Ethio Post",
    name: "የሰነዶች ጽፈት አገልግሎት",
    nameEn: "Document Writing Service",
    active: true,
  },

  // ─── 14. ፌዴራል ሰነድ ማረጋገጫ / Federal Document Authentication ──
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ውክልና",
    nameEn: "Power of Attorney",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "የመኖሪያ ቤት ሽያጭ",
    nameEn: "House Sale",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "የመኪና ሽያጭ",
    nameEn: "Car Sale",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ትርጉም",
    nameEn: "Translation",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ከሰነድ አረጋጋጭ ተቀም የሚመጡ ሰነዶች ማረጋገጥ",
    nameEn: "Document Authentication",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "የኪራይ ውል",
    nameEn: "Rental Agreement",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "የብድር ውል",
    nameEn: "Loan Agreement",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "መሻሪያ",
    nameEn: "Amendment",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ውል ቀሪ ማድረጊያ",
    nameEn: "Contract Termination",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ኑዛዜ",
    nameEn: "Will/Testament",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "መመስረቻ",
    nameEn: "Establishment Document",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ቃለ ጉባኤ",
    nameEn: "Meeting Minutes",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ኮፒ ማመሳከሪያ",
    nameEn: "Copy Certification",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "በስጦታ የማስተላለፍ ውል",
    nameEn: "Gift Transfer Agreement",
    active: true,
  },
  {
    dept: "ፌዴራል ሰነድ",
    deptEn: "Federal Document",
    name: "ቃለ መሃላ ማረጋገጫ",
    nameEn: "Oath Certification",
    active: true,
  },

  // ─── 15. መብራት ሃይል / Light & Power ──────────────────────
  {
    dept: "መብራት ሃይል",
    deptEn: "Light & Power",
    name: "የካርድ ብዛት",
    nameEn: "Card Count",
    active: true,
  },

  // ─── 16. መሶብ ፋይዳ / Mesob Faida ──────────────────────────
  {
    dept: "መሶብ ፋይዳ",
    deptEn: "Mesob Faida",
    name: "ናሽናል አይዲ ማስተካከያ",
    nameEn: "National ID Correction",
    active: true,
  },
  {
    dept: "መሶብ ፋይዳ",
    deptEn: "Mesob Faida",
    name: "ናሽናል አይዲ ምዝገባ",
    nameEn: "National ID Registration",
    active: true,
  },

  // ─── 17. ምግብና መድሃኒት / Food & Drug Control ──────────────
  {
    dept: "ምግብና መድሃኒት",
    deptEn: "Food & Drug",
    name: "የጤና ባለሙያዎች አዲስ የሙያ ፈቃድ",
    nameEn: "New Professional License",
    active: true,
  },
  {
    dept: "ምግብና መድሃኒት",
    deptEn: "Food & Drug",
    name: "የጤና ባለሙያዎች የሙያ ፈቃድ ዕድሳት",
    nameEn: "Professional License Renewal",
    active: true,
  },
  {
    dept: "ምግብና መድሃኒት",
    deptEn: "Food & Drug",
    name: "የጤና ባለሙያዎች የሙያ ፈቃድ ማሻሻያ",
    nameEn: "Professional License Amendment",
    active: true,
  },

  // ─── 18. ጤና / Health Services ──────────────────────────────
  {
    dept: "ጤና",
    deptEn: "Health",
    name: "የመንጃ ፈቃድ ጤና ምርመራ ሜዲካል ሰርተፊኬት",
    nameEn: "Medical Certificate for Driving License",
    active: true,
  },

  // ─── 19. Banks ──────────────────────────────────────────────
  {
    dept: "ንግድ ባንክ",
    deptEn: "Commercial Bank",
    name: "የትራንዛክሽን ብዛት",
    nameEn: "Transaction Count",
    active: true,
  },
  {
    dept: "ንግድ ባንክ",
    deptEn: "Commercial Bank",
    name: "የተሰበሰበ ገንዘብ መጠን",
    nameEn: "Collected Amount",
    active: true,
  },
  {
    dept: "ስኬት ባንክ",
    deptEn: "Success Bank",
    name: "የትራንዛክሽን ብዛት",
    nameEn: "Transaction Count",
    active: true,
  },
  {
    dept: "ስኬት ባንክ",
    deptEn: "Success Bank",
    name: "የተሰበሰበ ገንዘብ መጠን",
    nameEn: "Collected Amount",
    active: true,
  },

  // ─── 20. Ethiotelecom ──────────────────────────────────────
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "SIM Replacement",
    nameEn: "SIM Replacement",
    active: true,
  },
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "New Telebirr Activation",
    nameEn: "New Telebirr Activation",
    active: true,
  },
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "New SIM Sold",
    nameEn: "New SIM Sold",
    active: true,
  },
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "Mobile Handset",
    nameEn: "Mobile Handset",
    active: true,
  },
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "Cash In",
    nameEn: "Cash In",
    active: true,
  },
  {
    dept: "Ethiotelecom",
    deptEn: "Ethiotelecom",
    name: "Transfer Ownership",
    nameEn: "Transfer Ownership",
    active: true,
  },
];

module.exports = SERVICES;
